### ISSUE TITLE
Drop-off location not set

### ISSUE THREAD

**Issue by ashottonoyan** [uber/rides-ios-sdk#10]
Originally we were using `uber://?action=setPickup&pickup=my_location&dropoff[latitude]=%f&dropoff[longitude]=%f&dropoff[nickname]=%@` for launching Uber app with drop-off location already set. It works fine with deep-linking, but with the SDK, the nickname or address is pre-filled, but the drop-off pin is missing.

**Comment by ashottonoyan** [comment]
Integrating the SDK took me many hours of struggle and it's disappointing to see it working worse than deep-linking.

**Comment by faarwa** [comment]
What's the deeplink that is generated with the SDK for your parameters? You can add logging `print(deeplinkURL)` in RequestDeeplink.swift in the execute() function and copy and paste the output here. 

I apologize for the troubles you've had integrating with the iOS SDK. We're continually working on improving it and appreciate contributions from developers like you in helping us do so. I will gladly work with you to solve these issues.

**Comment by ashottonoyan** [comment]
uber://?action=setPickup&pickup%5Blongitude%5D=-73.9878441&dropoff%5Blongitude%5D=44.517979&dropoff%5Bnickname%5D=Bikini%20Bar%20Sip%20%26%20Surf&pickup%5Blatitude%5D=40.7484404&client_id=kaNN4O3_5RVoiveeS49mBl_xLJ8Vl4-A&dropoff%5Bformatted_address%5D=148%20Duane%20St%2C%20New%20York%2C%20NY%2010013%2C%20United%20States&product_id=b8e5c464-5de2-4539-a35a-986d6e58f186&dropoff%5Blatitude%5D=40.169016&user-agent=rides-button-v0.1.0

**Comment by faarwa** [comment]
At initial look, the drop-off location latitude/longitude do not point to a NY address which might be the issue you are running in to. The nickname and formatted address are for visual purposes, but the latitude and longitude parameters determine where the drop-off pin is shown. I think you'd be able to see the drop-off pin for your example if you zoom out far enough (see below).

![img_8404](https://cloud.githubusercontent.com/assets/2192960/12568455/e88bc7e4-c37a-11e5-8499-4e8bcf11b29c.PNG)

Try setting the longitude for the dropoff location to: -74.008200. Please let me know if this resolves the issue!

**Comment by ashottonoyan** [comment]
Sorry, I had set the wrong drop-off location. Thank you!
