### ISSUE TITLE
Uber native login flagging error

### ISSUE THREAD

**Issue by MukeshMuteja786** [uber/rides-ios-sdk#100]
I am currently running the example codes provided by Uber SDK (Swift  version).

I encounter a problem when I clicked on the Native Login 
After setting up the app in Uber and also copied the Client ID to the info.plist, I counter the error below:

When I click at the Login Button,  Uber App open and flag a UIAlert with a message of "There seems to be a problem connecting to Uber. Please go back to AppName and try again". What could be the problem? and not redirecting to my application

Btw, I fill in the redirect URL as "myapp://oauth/callback" on both the dashboard and the app info.plist.

Anything I miss out during the setup of this example?

Thanks.

**Comment by jbrophy17** [comment]
Hi @MukeshMuteja786 sorry to hear you're having trouble. Not redirecting back to your app sounds like there could be an issue with how you have your redirect URL set up. I see that you added the url to your dashboard and the info.plist. Did you also add "myapp" as one of the URL types recognized by your app? You can either do this via the Info tab of your application target or by adding the following to your info.plist:

```plist
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>myapp</string>
			</array>
		</dict>
	</array>
```

You also need to make sure that you have added your app's Bundle ID to the dashboard, in the App Signature field.

**Comment by MukeshMuteja786** [comment]
Firstly Thank you for support and Faster Reponse ...
Now App Redirecting Back but with error
Error Domain=com.uber.rides-ios-sdk.ridesAuthenticationError Code=18 "The Redirect URI provided did not match what was expected." UserInfo={NSLocalizedDescription=The Redirect URI provided did not match what was expected.}

**Comment by jbrophy17** [comment]
That error indicates that the redirect you specified in your info.plist
doesn't match exactly what you have listed on the developer dashboard.

If on the dashboard I am using "exampleapp://connect" then for the callback
in my info.plist I would also have "exampleapp://connect". And in my url
types I would only need the scheme, "exampleapp"

**Comment by MukeshMuteja786** [comment]
Please Help me to get Solve this issue. data on .plist :- is 


<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>myApp</string>
			</array>
		</dict>
	</array>


</array>
	<key>UberCallbackURIs</key>
	<array>
		<dict>
			<key>URIString</key>
			<string>myApp://connect</string>
			<key>UberCallbackURIType</key>
			<string>General</string>
		</dict>
		<dict>
			<key>URIString</key>
			<string>myApp://connect</string>
			<key>UberCallbackURIType</key>
			<string>AuthorizationCode</string>
		</dict>
		<dict>
			<key>URIString</key>
			<string>myApp://native_deeplink_callback</string>
			<key>UberCallbackURIType</key>
			<string>Native</string>
		</dict>

and Same "myApp://connect" URL on Dashboard  NSLocalizedDescription=The Redirect URI provided did not match what was expected

**Comment by MukeshMuteja786** [comment]
the information on .plist are:-
 <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>myApp</string>
            </array>
<key>UberCallbackURIs</key>
	<array>
		<dict>
			<key>URIString</key>
			<string>myApp://connect</string>
			<key>UberCallbackURIType</key>
			<string>General</string>
		</dict>
		<dict>
			<key>URIString</key>
			<string>myApp://connect</string>
			<key>UberCallbackURIType</key>
			<string>AuthorizationCode</string>
		</dict>
		<dict>
			<key>URIString</key>
			<string>myApp://native_deeplink_callback</string>
			<key>UberCallbackURIType</key>
			<string>Native</string>
		</dict>
	</array>

and on Dashboard link is same [myApp://connect](url)
error is same "NSLocalizedDescription=The Redirect URI provided did not match what was expected."

**Comment by MukeshMuteja786** [comment]
Thank you @jbrophy17  for your support and Faster response

**Comment by jbrophy17** [comment]
no problem :)
