### ISSUE TITLE
RidesClient has no member "fetchCheapestProduct"

### ISSUE THREAD

**Issue by tangert** [uber/rides-ios-sdk#107]
Not sure if this is the proper place to put this question, but I've been trying to follow along with the Uber button tutorial on the website (https://developer.uber.com/docs/rides/sdks/ios-button-enhanced#what-youll-need) and when I try to implement the code, apparently the library is missing some functions.

Not only do the classes in the SDK not contain things like "fetchCheapestProduct", but the SDK as a whole cannot even run its own example app.

**Comment by jbrophy17** [comment]
Hi @tangert sorry to hear you're having trouble. Could you give me some more information on what issue you're seeing? I am able to build and run the sample apps as expected, as well as call `fetchCheapestProduct` 

Are other parts of the SDK working for you?

**Comment by tangert** [comment]
For example, I literally just copied and pasted the sample button from the SDK tutorial on github, and I get this error:

<img width="869" alt="screen shot 2016-09-12 at 3 00 07 pm" src="https://cloud.githubusercontent.com/assets/11527126/18448556/a161b998-78f9-11e6-87be-9d1f94016a79.png">

This is in my viewDidLoad in a class that imports the `UberRides` pod.

Also, in my app delegate, I get this:

<img width="872" alt="screen shot 2016-09-12 at 3 02 28 pm" src="https://cloud.githubusercontent.com/assets/11527126/18448670/f7f24070-78f9-11e6-93d8-b69ac8ed4e70.png">

I can make a button just fine,  but there is key functionality that is making being able to follow easy tutorials very difficult, and I'm not sure what to do.

**Comment by jbrophy17** [comment]
Hmm, that is strange. How did you add the SDK to your app? Carthage or Cocoapods? And what version of Xcode are you using. Can you also check to make sure you installed the most recent version of the SDK?

**Comment by tangert** [comment]
I added via Cocoapods and I'm using Xcode 7.3. When I use cocoapods, it says this:

`Installing UberRides (0.4.2)`

**Comment by jbrophy17** [comment]
The problems you are seeing are because you are using an old version of the SDK, the most recent version is `0.5.2`. You should be able to update your version by running: 
```
pod update UberRides
```

**Comment by tangert** [comment]
Hm, trying now. It's getting stuck while trying to update but once it updates properly I'll let you know.

**Comment by tangert** [comment]
That fixed it! Got the button working. 👍

**Comment by jbrophy17** [comment]
Glad to hear it!
