### ISSUE TITLE
Error: access token failed to save to keychain

### ISSUE THREAD

**Issue by Sorix** [uber/rides-ios-sdk#109]
I’m using Swift 2.3, Uber installed via CocoaPods from branch swift-2.3-dev. I’m trying to call Uber with RideRequestViewController on device without Uber app. I’m using such code:

```swift
	func test() {
		let parameters = RideParametersBuilder().build()
		let loginManager = LoginManager()
		let rideRequestViewController = RideRequestViewController(rideParameters: parameters, loginManager: loginManager)

		presenterViewController.presentViewController(rideRequestViewController, animated: true, completion: nil)
	}
```

When Uber app is installed everything is okay, but if I’m using device without APP web authentication appears and after I enter my credentials nothing happens. At console log I see such errors every 2 seconds (infinite cycle):

> Consoul[3714:185086] -canOpenURL: failed for URL: "uberauth://connect?third_party_app_name=Consoul&callback_uri_string=Consoul://uberConnect&client_id=***&login_type=default&scope=ride_widgets&sdk=ios&sdk_version=0.5.2" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
>
> Error: access token failed to save to keychain

I have found similar issue #21, but solution proposed there doesn’t solve my problem:

> Just in case someone else faces a similar issue. This is a bug (not related to the sdk) that only happens when running the app from xcode directly on the phone. That's why when I relaunched the app the 2nd time works fine.

**Comment by Sorix** [comment]
I’ve just resolved that issue. To support web authentication your application need to have **Keychain Sharing entitlement** or you will receive `Error: access token failed to save to keychain` error. I’ve debugged that error and found that real error code is _34018: Internal error when a required entitlement isn't present_.

To add that entitlement in your application you need to go to Targets → Capabilities → Toggle **Keychain Sharing** to ON.
![keychain](https://cloud.githubusercontent.com/assets/5610904/18603088/9de61c94-7c7f-11e6-9ff8-71aa7c81c613.png)

**Comment by EPage-Ed** [comment]
I'm using SSO auth and the Swift 3 branch and just ran across this same issue.  Keychain Sharing is enabled for the app.  Login works fine without using the keychain in the login process.  When the keychain is used (set in configuration or the login call), the "access token failed to save to keychain" error occurs with the -34018 error code.

The error is occurring in KeychainWrapper in the setObject method code:

`        var result: OSStatus = SecItemAdd(keychainItemData as CFDictionary, nil)`

All of the parameters and properties in the setObject call look fine up until that point.
