### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by bennettl** [uber/rides-ios-sdk#110]
Is this SDK Swift 3 compatible? There seems to be something wrong with ObjectMapper, which seems to be a dependency of rides-ios-sdk
<img width="1280" alt="screen shot 2016-09-19 at 6 49 32 pm" src="https://cloud.githubusercontent.com/assets/1672224/18654955/e4de8624-7e99-11e6-983b-1f82fed7e51d.png">

**Comment by jbrophy17** [comment]
See #60 there is currently a swift-3-dev branch for working towards Swift 3 compatiblity, but it is not currently supported
