### ISSUE TITLE
iOS 10 compatibility - Cannot convert SDK to Swift 3 (Xcode 8)

### ISSUE THREAD

**Issue by quanghd** [uber/rides-ios-sdk#113]
My application has crashed on iOS 10. I fixed the bug and build a new version on Xcode 8. The Uber iOS SDK seems cannot to convert to Swift 3 to build.

**Comment by jbrophy17** [comment]
see #60

There is also the swift-3-dev branch, if you make a change to the SDK towards Swift 3 support please consider making a PR!
