### ISSUE TITLE
Swift 3 Branch Working Solution.

### ISSUE THREAD

**Issue by kwstasna** [uber/rides-ios-sdk#115]
Big thanks to  https://github.com/long  

All I had to do to make it work was to replace, inside the Podfile, 

`pod 'UberRides'`

with

`pod 'UberRides', :git => 'https://github.com/long/rides-ios-sdk.git', :branch => 'swift-3-dev’`

This is a working solution until there is an official Swift 3 edition in master :smile: 
Have a nice weekend!
:dancer:

**Comment by saintjab** [comment]
@kwstasna 
Was xcode able to auto-generate the <UberRides-Swift.h> for you? I have pulling my hair off because of that. How did you get yours to work? I worked prior to me updating my xcode to 8.0 which automatically comes with Swift 3.0. Any help? Thanks

**Comment by nbgraham** [comment]
@saintjab auto-generate the what?

#111 is the pull request that potentially solves this

**Comment by kwstasna** [comment]
Yes you just have to install this pod that i wrote above and remove the `pod 'UberRides`.
@saintjab

**Comment by saintjab** [comment]
Sorry guys, I was talking about UberRides-Swift.h because I am trying to import the Uber into an Objective-C project so I needed a header bridge. Will check @nbgraham response.

**Comment by saintjab** [comment]
I have tried the branch but no joy yet. For some reason, I can't get xcode to generate a UberRides-Swift.h for me. Any one using this in objective-c code? Any tips? Thanks

**Comment by jbrophy17** [comment]
@saintjab sorry to hear you're having trouble using the SDK with Objective-C. Would you mind opening a separate issue and I can help you there

**Comment by saintjab** [comment]
@jbrophy17, I have opened a new issue #120 . Thanks

**Comment by edjiang** [comment]
Closing this in favor of #167
