### ISSUE TITLE
Cocoapods install issue

### ISSUE THREAD

**Issue by dylankbuckley** [uber/rides-ios-sdk#116]
Getting this error message using latest version of cocoa pods, on Sierra and Xcode8.
- `ObjectMapper (~> 2.0)` required by `UberRides (0.5.2)`

**Comment by jbrophy17** [comment]
To use the library with Xcode 8, you will need to use either swift 2.3 or swift 3, we have dev branches open (swift-2.3-dev and swift-3.dev) to add this functionality and are working towards a new release with support for these versions

**Comment by edjiang** [comment]
Closing in favor of #167
