### ISSUE TITLE
In Xcode 8 unable to use the uber sdk it says to convert the sdk to swift version 3

### ISSUE THREAD

**Issue by bh1r123** [uber/rides-ios-sdk#122]
Hi There,

Recently updated my xcode to 8.0 after that i am unable to build my application with uber sdk because uber sdk is using swift. apple updated swift version to 3.0 and they are asking forcefull conversation of old swift versions to latest 3.0 after converting the latest version i have seen lots of errors. So Can you help us to release the new sdk with version 3.0.

Thank you and Regards,

**Comment by SNagra** [comment]
See issue #113

**Comment by jbrophy17** [comment]
#60 is the overall task for Swift 3 support, you can follow along there
