### ISSUE TITLE
Carthage/Checkouts Dependencies EMPTY

### ISSUE THREAD

**Issue by escully27** [uber/rides-ios-sdk#123]
When I try to manually add the UberRides SDK, the step with adding dependencies to the subproject causes issue. It appears the downloaded folder of Carthage/Checkouts has subfolders for the appropriate dependencies but they're empty. Same for the Swift SDK example project - it fails for the same reason. Any clarification would be great.

**Comment by jbrophy17** [comment]
Sorry to hear you're having trouble. Are you running into issues manually adding the SDK to your project or just with getting the example projects to build? 

The Carthage/Checkouts folder contains the git submodules for the dependencies, if you are seeing them empty, try running `git submodule update --recursive` and that should clone whatever is missing.

**Comment by escully27** [comment]
I'm having trouble while adding the SDK manually. I will try running the git update and let you know. I appreciate the help. 

Thanks,
Emmett Scully
630.303.2226

**Comment by escully27** [comment]
where do I run git submodule update --recursive?

**Comment by escully27** [comment]
I run into issues while adding it to my project, and with the example.

**Comment by escully27** [comment]
when i follow the instructions you gave here, I end up with everything working fine until I actually put 'import UberRides' - at which point I get no such module and have to start from scratch. plz help! https://github.com/uber/rides-ios-sdk/issues/18

**Comment by escully27** [comment]
Just kidding - got it to work! Lol thanks anyways. :)

**Comment by jbrophy17** [comment]
Hah, glad to hear it
What ended up being the problem? (might help someone in the future with the same issue)

**Comment by escully27** [comment]
My main project would run but crash immediately, with barely any error output 
`dyld`dyld_fatal_error:
->  0x1200ad088 <+0>: brk    #0x3`
I needed to put the ObjectMapper.framework in the UberRides.proj Linked Frameworks, but also in my main projects embedded binaries. Seemed to shut xcode up.

**Comment by jbrophy17** [comment]
Closing this since you got it to work
