### ISSUE TITLE
Xcode 8 Error

### ISSUE THREAD

**Issue by ivangarcialopez** [uber/rides-ios-sdk#126]
Hello,

We are using CocoaPods to integrate the SDK into a Swift 3 and Xcode 8. Everything works fine but when I try to build the project I get this error: framework not found ObjectMapper.

This is the command we use in the pod file: pod 'UberRides'. The version being installed is: Installing UberRides (0.5.2).

Do I need to add the whole library manually?

Kind regards,

Ivan

**Comment by jbrophy17** [comment]
Hi @ivangarcialopez, this is likely related to #60 around Swift 3 support. Would you mind sharing what you have in your podfile regarding UberRides?

**Comment by ivangarcialopez** [comment]
Hi, thanks for the answer. This is my Pod File.

# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyApp' do
    
    pod 'GoogleMaps'
    pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
#    pod 'Alamofire', '~> 4.0'
	pod 'UberRides'
end

**Comment by ivangarcialopez** [comment]
Hello, I had to stop this project for a while but I'm working on it again. I've tried different approaches but still the same problem. The build is always failing because
**_Showing All Issues
ld: framework not found ObjectMapper_**

I've tried with this pod line:
pod 'UberRides', :git => 'https://github.com/long/rides-ios-sdk.git', :branch => 'swift-3-dev’

**Comment by ivangarcialopez** [comment]
I finally installed the library directly to my project and is working. I've used the Swift-3 branch.

**Comment by mithuregarsun** [comment]
Using ObjectMapper (1.5.0)
Using UberRides (0.6.0)
Generating Pods project
Integrating client project
why show Error in Terminal
