### ISSUE TITLE
Shared credentials across iOS app and extension

### ISSUE THREAD

**Issue by SNagra** [uber/rides-ios-sdk#127]
I am trying to share one set of credentials across an iOS app and it's app extension. I've turned on Keychain Sharing in both targets and added the same bundle identifier to both. When configuring the SDK I set 
`
Configuration.setDefaultKeychainAccessGroup("com.identifier")
`

and I double check that it is set appropriately with

`
print(Configuration.getDefaultKeychainAccessGroup())
`

However, when I try and use the SDK to create a ride in the extension, the request returns this error:
`
"Invalid OAuth 2.0 credentials provided."
`

**Comment by jbrophy17** [comment]
Thanks for the report. Taking a look at the Keychain Manager, it looks like there is a bug where the KeychainAccessGroup is not correctly being used when saving the credentials.

**Comment by SNagra** [comment]
Any suggested workarounds?

**Comment by jbrophy17** [comment]
Sorry for the delay, this is fixed in [v0.5.3](https://github.com/uber/rides-ios-sdk/releases/tag/v0.5.3)
