### ISSUE TITLE
Empty scope returned from SSO login in new Uber app v3.219.12

### ISSUE THREAD

**Issue by samwize** [uber/rides-ios-sdk#128]
In the new Uber app released on 4 Nov, there is a critical breaking change.

During a SSO login, the granted scope is empty, even though the requested scope is indeed given.

In AccessToken.swift L108, scopesString now erroneously has `%20` instead of space. Example: it should be `profile ride_widgets` instead of `profile%20ride_widgets`.

**Comment by jbrophy17** [comment]
Looks like a url encoding issue, thanks for bringing this up, going to look into it right now

**Comment by jbrophy17** [comment]
Found the issue with the encoding, working on a fix. In the meantime, your access tokens still work correctly for the requested scopes, it is just a bug with correctly notifying you which scopes were requested

**Comment by jbrophy17** [comment]
Sorry on the delay here, SSO should be correctly returning scopes now as of Uber version 3.221

No SDK update is necessary
