### ISSUE TITLE
iOS Deep Link Pickup Location Stopped Working

### ISSUE THREAD

**Issue by eddie-herdemian** [uber/rides-ios-sdk#129]
With the new version of the Uber app we're noticing that when we try to pre-populate the pickup location via a deep link from our app it doesn't work (its set to the users location).  This works fine with previous versions of the Uber app.

What is the ETA & plan for this to be resolved?

This is the deep link we're using, which is live in the Levi's Stadium app:

`uber://?client_id=<client_id>&action=setPickup&pickuplatitude=37.413213&pickuplongitude=-121.976760&pickupnickname=LevisStadium&product_id=a1111c8c-c720-46c3-8534-2fcdd730040d`

**Comment by jbrophy17** [comment]
Your deeplink is malformed. You are missing some square brackets around latitude, longitude, and nickname
Please try `uber://?client_id=ssuk1NUkjdys8llCRRqJzLHSkBkDNFHV&action=setPickup&pickup[latitude]=37.413213&pickup[longitude]=-121.976760&pickup[nickname]=LevisStadium&product_id=a1111c8c-c720-46c3-8534-2fcdd730040d` and let me know if it works

**Comment by dustinwhittle** [comment]
The deep link is malformed and the app is not checking if uber is available to open the link: https://developer.uber.com/docs/riders/ride-requests/tutorials/deep-links/introduction

`if ([[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"uber://"]]) {
    // Uber app is installed, construct and open deep link.
} else {
    // No Uber app, open the mobile site.
}`
