### ISSUE TITLE
Accept CLLocation parameter instead of coordinates as double?

### ISSUE THREAD

**Issue by sachinkesiraju** [uber/rides-ios-sdk#13]
Passing lat/long as double values for the coordinates doesn't seem as clean as simply passing a CLLocation object (easier to directly use with Core Location's user location). [As used in UberKit: github.com/sachinkesiraju/UberKit]

**Comment by faarwa** [comment]
You're right that a `CLLocation` object makes more sense to pass around. For the beta release of the SDK, we didn't want to force use of `CoreLocation` just to use the `RequestButton` which just deep links to the Uber app. When the SDK is built out to expose all the endpoints, it'll make more sense to use the `CLLocation` object. In the meantime, the `location.coordinate.latitude/longitude` properties can be passed in if using `CoreLocation`. I'll leave this open. Thanks!

**Comment by jbrophy17** [comment]
Fixed in [v0.4.0](https://github.com/uber/rides-ios-sdk/releases/tag/v0.4.0)
