### ISSUE TITLE
Dropoff location nickname is not displayed

### ISSUE THREAD

**Issue by clairebear** [uber/rides-ios-sdk#130]
I want to show a uber UBSDKRideRequestButton in our app, and once user clicks the button, user is redirected to Uber App, they would see destination location. 

However, when I set the dropoff location nick name, it's not shown in uber app.

Here is my code

`    // create parameters builder
   UBSDKRideParametersBuilder *builder = [[UBSDKRideParametersBuilder alloc] init];
   [builder setPickupLocation: pickupLocation];
   [builder setDropoffLocation:dropoffLocation nickname:@"Airport" address:@"Auckland"];
    
    __weak typeof(self) weakSelf = self;
    
    // fetch ride estimate
    [self.ridesClient fetchCheapestProductWithPickupLocation: pickupLocation
                                                  completion:^(UBSDKUberProduct* product, UBSDKResponse* response) {
        
        // The product ID must be set in order to show any metadata.
        if (product) {
            [builder setProductID: product.productID];
            weakSelf.rideRequestButton.rideParameters = [builder build];
            // Manual refresh for the ride information on the button.
            [weakSelf.rideRequestButton loadRideInformation];
            
        }
    }];`

I check if the nick name is set property before we manually load the information on button, and I can see they are set correctly.

![screen shot 2016-11-18 at 11 23 10 am](https://cloud.githubusercontent.com/assets/3312306/20410994/7b8a1142-ad84-11e6-8031-a03684996160.png)

However, when we click the button and launch the uber app, the nickname is not displayed, instead it shows "Dropoff Location"

![img_0006](https://cloud.githubusercontent.com/assets/3312306/20411143/1f58a900-ad85-11e6-94c4-d2f2dcb0669e.PNG)

Does anyone have the same issue?
I pretty much followed the example that is given by uber.

**Comment by jbrophy17** [comment]
Thanks for the report! This is a bug in the app itself, and will be fixed in the next version, sorry for the inconvenience. I will keep this issue open until the new version is released, though no SDK update will be necessary

**Comment by clairebear** [comment]
@jbrophy17 Thank you so much for your response. We are releasing our iOS app soon, it would be good for us to know the time frame of uber next release. Please keep us updated.

**Comment by jbrophy17** [comment]
This is now fixed in Uber version 3.222.3
