### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by kajensen** [uber/rides-ios-sdk#131]
Its November 18 and you don't support swift 3... wowza

**Comment by jbrophy17** [comment]
#110

**Comment by Samavesh123** [comment]
Its May 5 2017 and they dont support Swift 3. Shame!!!

**Comment by tyvsmith** [comment]
@Samavesh123 This might interest you https://github.com/uber/rides-ios-sdk/tree/swift-3-dev. Once we have more resources after a current project, we'll get that merged to master after a bit of API cleanup.

Thanks for your patience!
