### ISSUE TITLE
Provide me cocoa pods for Swift 3

### ISSUE THREAD

**Issue by NiteshKhandal** [uber/rides-ios-sdk#135]
These cocoa pods are in swift 2.3 but i have use swift 3 in my project. so i face converting problem.
 so please provide me cocoa pods which are support swift 3 as soon as possible.

and please look into this and let me know. on this mail ID rohitsharma180593@gmail.com

**Comment by gloffreda** [comment]
use this for while

pod 'UberRides', :git => 'https://github.com/long/rides-ios-sdk.git', :branch => 'swift-3-dev’ 

Works great

**Comment by jbrophy17** [comment]
Swift 3 support is in the works, please follow along on #60
