### ISSUE TITLE
UberRides/UberRides-Swift.h' file not found

### ISSUE THREAD

**Issue by Saravana181187** [uber/rides-ios-sdk#137]
When I run the Sample Objective-c project the error found like ,
UberRides/UberRides-Swift.h' file not found
How to solve this?

**Comment by jbrophy17** [comment]
Hi @Saravana181187 before you can use the sample apps, you will need to build the dependencies with Carthage.

Run the following command in the root directory of the sample app you want to build
```
carthage update --platform iOS
```

And then this issue should go away

**Comment by Saravana181187** [comment]
Hi @jbrophy17 If I create a Own Sample Project for Uber Integration using CocoaPods using the following command it have show some issues.

> pod UberRides


The issues are..
`public func toJSON() -> [String: AnyObject] {
		return Mapper<<#N: Mappable#>>().toJSON(self) --->Expected expression after operator
	}`

 

>  Header 'ObjectMapper-Swift.h' not found

> Could not build Objective-C module 'ObjectMapper'

> UberRides/UberRides-Swift.h' file not found

Please Say the Detail for Installing using pods and how to solve these issues.

**Comment by Saravana181187** [comment]
Hi @jbrophy17 If UberRides is support for objective-c swift 3 or not and If it is possible to Installing Cocoa pods in Objective-c Project.

**Comment by edjiang** [comment]
Closing since this issue is from before the Swift 3 release

**Comment by sanjeev1994** [comment]
Hi , 
I created a new obj-c project and tried to add Uber SDK.  I installed it via cocoa pods.

I am getting this error - 'UberRides/UberRides-Swift.h' file not found

is there any solution for this?

**Comment by ZvOlCuOk2009** [comment]
@jbrophy17 jbrophy17 Thanks!.. helped me...
