### ISSUE TITLE
If UberRides is support for objective-c and swift 3 or not while Installing from Cocoa pods.

### ISSUE THREAD

**Issue by Saravana181187** [uber/rides-ios-sdk#139]
If I create a Own Sample Project for Uber Integration using CocoaPods using the following command it have show some issues.In my main project already I will use some SDK in cocoa pods so I want to install the UBER SDK from the cocoa Pods not from carthage but while installing from cocoa pods it getting issues like below so please say how can I installing the SDK from cocoa pods in Objective-c Project.

If it is possible to Installing from Cocoa pods in Objective-c Project.

pod UberRides
The issues are..
public func toJSON() -> [String: AnyObject] { return Mapper<<#N: Mappable#>>().toJSON(self) --->Expected expression after operator }

Header 'ObjectMapper-Swift.h' not found
Could not build Objective-C module 'ObjectMapper'
UberRides/UberRides-Swift.h' file not found
Please Say the Detail for Installing using pods and how to solve these issues.

**Comment by jbrophy17** [comment]
Hi @Saravana181187 are you having trouble install the SDK into an Objective-C project? Are any of the other SDKs you are using Swift 3?

**Comment by Saravana181187** [comment]
Hi @jbrophy17 yes I have trouble in install the SDK into an Objective-C, I don't have using any other SDKs for Swift 3, I have the following troubles when i installing the SDK in Project.

Here I Have attached the screen shots of the Issues.

![screen shot 2016-12-02 at 12 33 07 pm](https://cloud.githubusercontent.com/assets/8847867/20825692/f03f4428-b88b-11e6-8005-6f6ba92ed5e3.png)
![screen shot 2016-12-02 at 12 33 44 pm](https://cloud.githubusercontent.com/assets/8847867/20825708/01a15b84-b88c-11e6-9dff-d200cb208f4c.png)
![screen shot 2016-12-02 at 12 34 01 pm](https://cloud.githubusercontent.com/assets/8847867/20825709/01a97ec2-b88c-11e6-863e-6d11d026f54c.png)

**Comment by googler2013** [comment]
@jbrophy17  @Saravana181187  Any update, I am facing same issue...

**Comment by jbrophy17** [comment]
Can you include what you are using for your podfile? 

I would suggest taking a look at #60 which I have just updated with how to use the `swift-3-dev` branch for swift 3 support

**Comment by edjiang** [comment]
Closing this issue in favor of #167
