### ISSUE TITLE
How to Install SDK from Cocoa Pods?

### ISSUE THREAD

**Issue by Saravana181187** [uber/rides-ios-sdk#140]
How to Install the SDK from Cocoa Pods for Objective-c and Swift 3, Please say step by step for to easy understanding.?

**Comment by jbrophy17** [comment]
Hi @Saravana181187 currently we do not have Swift 3 support, so the issues you are seeing are likely related to that, not cocoapods.

See #60

**Comment by Saravana181187** [comment]
Hi @jbrophy17 Thank you Kind of your reply, I will check and work with in swift 2.3 version.
