### ISSUE TITLE
How to install SDK in old objective-c project with Cocoa Pods, please say detail in step by step?

### ISSUE THREAD

**Issue by Saravana181187** [uber/rides-ios-sdk#142]
How to Install the SDK in old objective-c project with cocoa pods. If I Installing in Pod using the following command It getting lot of issues that has make very difficult me and I unable to Solve that.

> `use_frameworks!
target 'My Project Name' do
pod 'UberRides'
end

And the Using this Command..

`$ pod install`

 Can you please say Detail and Please say step by step for to easy understanding.?

**Comment by suriksarkisyan** [comment]
@Saravana181187 you can try to use Carthage for UberRides SDK and other swift frameworks.

**Comment by Saravana181187** [comment]
@suriksarkisyan I want to Install from cocoa pods not in carthage please say about that, If it is possible or not.

**Comment by suriksarkisyan** [comment]
@Saravana181187, yes you can. But you will get some problems with other frameworks as you see. You can try to fix them or you can use Carthage. That problems occur because of `use_frameworks!`. I  know only two ways to avoid this issues: fix them manually or use Carthage. Maybe somebody else can  help you, sorry.

**Comment by jbrophy17** [comment]
It is possible that this is due to conflicting versions of Swift in pods that you are trying to use. Once the SDK has been updated to Swift 3 (#60) your problems might be fixed

**Comment by ivhpMX** [comment]
Hi,
I am using Carthage to install Uber SDK, my project is build in Objective c; my Xcode is 8.2.1 and on the last part of the tutorial, when I need to set the Embedded Content Contains Swift Code flag to YES in the Build Settings tab, that option doesn't show to me and I cannot add it to my project; What else I need to do to install correctly the API?

Thank you!

**Comment by suriksarkisyan** [comment]
@ivhpMX  [this](http://stackoverflow.com/a/39049584/6015308) will help you :)

**Comment by edjiang** [comment]
Closing since it seems like a language version problem. See #167 for how to use this SDK with Swift 3.
