### ISSUE TITLE
We are waiting for the Latest SDK for Support swift 3?

### ISSUE THREAD

**Issue by FactumGame** [uber/rides-ios-sdk#148]
We are waiting for the Latest SDK for Support swift 3?

**Comment by chrisvanbuskirk** [comment]
Let me echo that.  What gives Uber?

**Comment by jbrophy17** [comment]
Hello, sorry for the delay, I have just updated #60 with the latest information. Please use that thread for all Swift 3 related discussion

**Comment by FactumGame** [comment]
Ok thx

2016-12-29 19:57 GMT+03:00 John Brophy <notifications@github.com>:

**Comment by chrisvanbuskirk** [comment]
Thank you!
