### ISSUE TITLE
Swift 3 + Carthage temporary fix

### ISSUE THREAD

**Issue by scottrhoyt** [uber/rides-ios-sdk#154]
If anyone, like me, needs a quick fix for making UberRides work with Swift 3 and Carthage, I made a couple quick fixes to @long's great work for #111. Drop this is your Cartfile:

```
github "scottrhoyt/rides-ios-sdk" "swift-3-dev"
```

**Comment by edjiang** [comment]
Thanks for this note, @scottrhoyt!

Closing this in favor of #167 for now :)
