### ISSUE TITLE
Fare expired

### ISSUE THREAD

**Issue by Xioshock** [uber/rides-ios-sdk#155]
Hey,
I have kinda weird problem, I'm using the widget from this sdk in the following way:

```
let behavior = RideRequestViewRequestingBehavior(presentingViewController: self)
let dropOff = CLLocation(latitude: event.coordinate.latitude, 
    longitude: event.coordinate.longitude)
		
let parameters = RideParametersBuilder().setDropoffLocation(dropOff).build()
		
behavior.requestRide(parameters)
```
but for some reason, in doesn't work as expected in the USA. When I select uberPool and request a ride, popup appears with "fare expired" message. However when I request uberX, it works just fine.

Even weirder is that it works in Czech republic even with uberPool.

Is there any reason for this message, is this expected behavior? Because it doesn't look like it.

I read somewhere that it may be related to "surging".

**Comment by jbrophy17** [comment]
Hi @Xioshock thanks for the report! Your intuition was correct, this is not the expected behavior. We are working to fix this on our side, no SDK update or changes will be required for your app. I'll update this thread when it has been fixed.

**Comment by jbrophy17** [comment]
This issue should now be resolved. No updates to the SDK are necessary
