### ISSUE TITLE
Small Button

### ISSUE THREAD

**Issue by Victorgf87** [uber/rides-ios-sdk#156]
Hello, I have seen in the documentation https://d1a3f4spazzrp4.cloudfront.net/uberex/Uber_API_Design_Guidelines_20160329.pdf that a small button can be created. How could I do that?

Thanks for your help

**Comment by jbrophy17** [comment]
Hi @Victorgf87 currently we do not provide a version of that small button. But you could subclass the LoginButton to create something based on that design

**Comment by Victorgf87** [comment]
Thank you, @jbrophy17 , I will try to do that 👍 
Sorry for the delay, I was very busy :)
