### ISSUE TITLE
A more detailed documentation on how to test the app

### ISSUE THREAD

**Issue by giolegaspijr** [uber/rides-ios-sdk#158]
I'm done implementing Uber SDK in my app using the existing documentations that you have. (thanks for putting them all up for us 👍 ). Now I wanted to start testing the app using the sandbox environment as mentioned in Uber's API documentation website. The problem is, they're all pointing to terminal requests and commands to test it. I'm just wondering if there's a document that we can use as a guide in testing the Uber functionalities like update ride request status, getting real-time ride request status, change any data on the fly within the app.... Also, just an additional question... Is it possible to test it by going thru the actual Uber process (request for a real ride, use it[on-trip] and pay) even the sandbox is enabled? I tried it twice and both of my dev accounts were blocked.

Thanks and happy coding!

**Comment by giolegaspijr** [comment]
I posted a question in stackoverflow for the code snippet and more details of what I wanted to have.
http://stackoverflow.com/questions/42387082/uber-sdk-for-ios-get-real-time-ride-request-status-made-via-deep-link

Again, Thanks!

**Comment by giolegaspijr** [comment]
Hello again guys,

I commented on the answer in my stackoverflow post.
https://stackoverflow.com/questions/42387082/uber-sdk-for-ios-get-real-time-ride-request-status-made-via-deep-link

Please help me with my problem. Thanks in advanced!

**Comment by edjiang** [comment]
Replied in StackOverflow; closing this thread on GitHub so we can stay in one thread :)
