### ISSUE TITLE
New Uber Logo

### ISSUE THREAD

**Issue by SNagra** [uber/rides-ios-sdk#16]
Will there be an update soon to incorporate the new Uber logo?

**Comment by faarwa** [comment]
Yup! This will be updated in the next release.

**Comment by SNagra** [comment]
We are hoping to submit to Apple within the next 24 hours, do you anticipate the next release will be within the next day or 2, or should we just update to the new release in a future update?

Thanks!

**Comment by faarwa** [comment]
Unfortunately this won't be released in the next few days, it'll most likely be within the next few weeks.

**Comment by jbrophy17** [comment]
Fixed in [v0.4.0](https://github.com/uber/rides-ios-sdk/releases/tag/v0.4.0)
