### ISSUE TITLE
Issues when upgraded from swift 2.3 to Swift3

### ISSUE THREAD

**Issue by Jeesson7** [uber/rides-ios-sdk#160]
I migrated my project to swift 3 from 2.3. when I try to update my pods i get downgraded from uber 0.6.0 to 0.3.1.  I tried this because ObjectMapper is included as a dependency to UberRides and version 1.5.0 is the default dependency when I installed uberRides  in Xcode 7.3. However Object Mapper has swift 3 support from version 2.0 only. I upgraded ObjectMapper to 2.0 to satisfy it forcibly

pod 'ObjectMapper', '2.0'

however UberRides was downgraded to 0.3.1 while doing so. I forcibly try to update the uberRides to 0.6.1 .however in Terminal i get a message like this->

[!] Unable to satisfy the following requirements:

- `ObjectMapper (= 2.0)` required by `Podfile`
- `ObjectMapper (~> 1.0)` required by `UberRides (0.6.0)`

**Comment by edjiang** [comment]
Hey @Jeesson7,

Please take a look at #167 for instructions on how to import this SDK in a Swift 3 project. Thanks!
