### ISSUE TITLE
RideRequestView doesn't display a map. 

### ISSUE THREAD

**Issue by Igorsnaki** [uber/rides-ios-sdk#161]
Hi all! 
I tried to use Ride Request Widget. 
I did all steps as described in doc : https://developer.uber.com/docs/riders/ride-requests/tutorials/widget/ios 

When I add RideRequestView or present RideRequestViewController , there is no map on screen : 

![img_2222](https://cloud.githubusercontent.com/assets/24248360/24956955/a6f626ce-1f92-11e7-9ea4-3e83db98e318.PNG)

Any ideas how to fix it? 

Thank you in advance. 

The same issue on example project from :  https://github.com/uber/rides-ios-sdk  on branch : "swift-3-dev" 
The same issue on Android sample application

**Comment by arogal** [comment]
Hi there,

Unfortunately, the current version of the widget does not contain a map. I'll leave this issue open for now and close it once it does, but we do not have an ETA for that at the moment.

**Comment by ddudek** [comment]
Does anyone have a workaround for this? It would be great to show just the address widgets and even implement the map by ourselves

**Comment by edjiang** [comment]
@ddudek: you can build the ride request flow manually using the `RidesClient`, and create your own UI elements to match. Otherwise, you can use the Ride Request Deeplink to link users into the Uber app.

**Comment by ddudek** [comment]
Probably yes, these are the only ways. Although implementing all the widgets like selecting ride type, payment options, autosuggestions for destination and pick up - a lot of work needed.

How big is the problem with implementing map in the view above? Maybe it would be easier to help with implementing the map, than writing all by ourselves from scratch.

**Comment by edjiang** [comment]
@ddudek: the ride request widget is actually a webview, so changes would be required there. 

What does your timeline look like?

**Comment by ddudek** [comment]
Hm, we have an app currently in ongoing development, a bit polishing left, and the issue described here. But if it's in the webview (and the underlying web page), are there any options?

**Comment by edjiang** [comment]
Gotcha. Yeah, unfortunately you would have to implement the above solution at the moment. 

You could try embedding a smaller widget, and embed your own map view. Then call the ride request api to get the car location and render it on the map.

**Comment by ddudek** [comment]
@edjiang We tried to hack it a bit, but smaller window and widget itself doesn't give us any callback when the user enters pickup or destination to show it on the map in any way.

Do you have any idea if there are any plans to have this working?

We'll go with implementing all from scratch, but please let me know if implementation on your side would come soon :D or if we can help in any way

**Comment by edjiang** [comment]
Ah yes, that's a good point. 

Unfortunately, I'm not sure how soon we will be able to provide a good solution for you. Thus I'd suggest building this yourself. 

So I can have better context while working with our team on solutions: what type of app are you building? Happy to jump on a call if you don't want to discuss on GitHub :)

**Comment by edjiang** [comment]
Ride Request Widget was deprecated in 0.9, so I'm closing this as a non-issue anymore. Sorry!

https://github.com/uber/rides-ios-sdk/releases/tag/v0.9.0

https://developer.uber.com/docs/riders/change-log
