### ISSUE TITLE
Updated Swift version (3.0)

### ISSUE THREAD

**Issue by vish02** [uber/rides-ios-sdk#163]
Dear support team,

I am using "UberRides" SDK in our iOS app which support only swift 2.3 version.
Now I am updating my code from swift 2.3 to swift 3.1. In that case it is giving many warnings 
and errors related to "ObjectMapper" classes. So I need the updated version of "UberRides" SDK  which can support swift updated version. 
Please provide the updated SDK or any suggestion to give support of swift 3.1 version.
Any suggestion would be appreciated.

**Comment by varunbabu008** [comment]
I have the same error as well. Please Fix it

**Comment by MikeLeber117** [comment]
There is a branch where this seems to compile for Swift 3 https://github.com/uber/rides-ios-sdk/tree/swift-3-dev - However,  it looks like development has stopped in general on this SDK. Really wish they would get around to updating things.

**Comment by arogal** [comment]
Hi MikeLeber117

We're definitely coming back to this. Please stay tuned.

Thanks for your patience.

**Comment by naturalwarren** [comment]
I'm writing a new app and tried to bring in the UberRides SDK using Cocoapods and ran into this. My app won't compile when I add `pod 'UberRides'` to my pod file.

**Comment by varunbabu008** [comment]
Hey @naturalwarren Please replace the pod 'UberRides' with 
pod "UberRides", :git => "https://github.com/uber/rides-ios-sdk.git", :branch => "swift-3-dev"

**Comment by edjiang** [comment]
Closing in favor of #167
