### ISSUE TITLE
Using the Uber Rides SDK with Swift 3

### ISSUE THREAD

**Issue by edjiang** [uber/rides-ios-sdk#167]
Hey Everyone!

I recently joined the Uber team and will be taking over development and maintenance of this project. We know that this SDK greatly needs some love, so I'm working to triage and figure out next steps for this SDK.

For clarity (since there are many GH issues opened on this subject), here's how to install the SDK in a Swift 3 project:

## CocoaPods

```ruby
pod 'UberRides', :git => 'https://github.com/uber/rides-ios-sdk.git', :branch => 'swift-3-dev'
```

## Carthage

```
github "uber/rides-ios-sdk" "swift-3-dev"
```

**Comment by karthikasdas** [comment]
Hi @edjiang ,

I tried to integrate Uber in this way and its not working.

Showing All Messages
  "__TMaC9UberRides17RideRequestButton", referenced from:
Showing All Messages
      __TFC11AirCrewClub26OfferDetailsViewController9tableViewfTCSo11UITableView12cellForRowAtV10Foundation9IndexPath_CSo15UITableViewCell in OfferDetailsViewController.o

OfferDetailsViewController.o is the name of the file where i try to use uber ride request button.

Regards,
Karthika

**Comment by edjiang** [comment]
Hey @karthikasdas, what's the exact error that you're having?

**Comment by edjiang** [comment]
We are now on v0.7.0, which adds Swift 4 support! If you are using Swift 3, you can still link to it when using Xcode 9. 

https://github.com/uber/rides-ios-sdk/releases/tag/v0.7.0
