### ISSUE TITLE
Getting warnings with Xcode 7.3

### ISSUE THREAD

**Issue by Kinectapp** [uber/rides-ios-sdk#17]
![screenshot 2016-03-25 01 49 08](https://cloud.githubusercontent.com/assets/16827983/14032419/2797cb42-f22c-11e5-932e-dfe0ff4d9540.png)

**Comment by faarwa** [comment]
Thanks for pointing this out! We'll update for our next release.

**Comment by Dershowitz011** [comment]
@faarwa selector syntax updated. Do merge the request! Thanks! :)

**Comment by jbrophy17** [comment]
Fixed in [0.5.0](https://github.com/uber/rides-ios-sdk/releases/tag/v0.5.0)
