### ISSUE TITLE
Apple mach o linker error when trying to use 

### ISSUE THREAD

**Issue by karthikasdas** [uber/rides-ios-sdk#172]
Hi,

I have been trying to use the following code and Xcode giving me compiler error with apple mach o linker error.

                        let ridesClient = RidesClient()
                        let lat = ((lat!)! as NSString).doubleValue as Double
                        let lon = ((lon!)! as NSString).doubleValue as Double
                        let dropoffLocation = CLLocation(latitude: lat, longitude: lon)
                        let pickupLocation = CLLocation(latitude: (latitude)!, longitude: (longitude)!)

                        var builder = RideParametersBuilder().setPickupLocation(pickupLocation).setDropoffLocation(dropoffLocation)
                        ridesClient.fetchCheapestProduct(pickupLocation: pickupLocation, completion: {
                            product, response in
                            if let productID = product?.productID {
                                builder = builder.setProductID(productID)
                                button?.rideParameters = builder.build()
                                button?.loadRideInformation()
                            }
                        })

If I comment them the app is working.

Kindly suggest!

Thanks,

**Comment by edjiang** [comment]
Hey @karthikasdas,

Try out the new release and let me know if this solves your problems. https://github.com/uber/rides-ios-sdk/releases/tag/v0.7.0
