### ISSUE TITLE
Not able to use SDK in Xcode 8.3.3..

### ISSUE THREAD

**Issue by developweb10** [uber/rides-ios-sdk#173]
I am getting error when i compile my code. I also updated podfile but getting same issue please check this screen shot.
![screen shot 2017-08-18 at 12 49 43 pm](https://user-images.githubusercontent.com/7962363/29448355-e120d14c-8413-11e7-9537-55db5f2cb00a.png)

**Comment by edjiang** [comment]
Hey @developweb10, are you using the instructions in this issue to install the SDK? https://github.com/uber/rides-ios-sdk/issues/167

**Comment by edjiang** [comment]
It seems like the `ObjectMapper` dependency is not being loaded correctly. Can you paste the contents of your `Podfile.lock` file?

That specific line that you highlighted has a syntax error. 

Another thing you can try is running `pod repo update` before `pod install`.

**Comment by eli7ah** [comment]
I have the same problem. Here is my **Podfile.lock**

`PODS:
  - DadaeduServices (1.0.0)
  - Firebase/Core (3.17.0):
    - FirebaseAnalytics (= 3.9.0)
    - FirebaseCore (= 3.6.0)
  - FirebaseAnalytics (3.9.0):
    - FirebaseCore (~> 3.6)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (3.6.0):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseInstanceID (1.0.10):
    - FirebaseCore (~> 3.6)
  - Google/Analytics (3.1.0):
    - Google/Core
    - GoogleAnalytics (~> 3.12)
  - Google/Core (3.1.0):
    - FirebaseAnalytics (~> 3.2)
  - Google/SignIn (3.1.0):
    - Google/Core
    - GoogleSignIn (~> 4.0)
  - GoogleAnalytics (3.17.0)
  - GoogleMaps (1.13.2)
  - GoogleSignIn (4.0.2):
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GoogleToolboxForMac/NSString+URLArguments (~> 2.1)
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSDictionary+URLArguments (2.1.1):
    - GoogleToolboxForMac/DebugUtils (= 2.1.1)
    - GoogleToolboxForMac/Defines (= 2.1.1)
    - GoogleToolboxForMac/NSString+URLArguments (= 2.1.1)
  - GoogleToolboxForMac/NSString+URLArguments (2.1.1)
  - GTMOAuth2 (1.1.4):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.1.11):
    - GTMSessionFetcher/Full (= 1.1.11)
  - GTMSessionFetcher/Core (1.1.11)
  - GTMSessionFetcher/Full (1.1.11):
    - GTMSessionFetcher/Core (= 1.1.11)
  - ObjectMapper (2.2.8)
  - SDWebImage (4.1.0):
    - SDWebImage/Core (= 4.1.0)
  - SDWebImage/Core (4.1.0)
  - UberRides (0.7.0):
    - ObjectMapper (~> 2.0)
  - VK-ios-sdk (1.4.6)

DEPENDENCIES:
  - DadaeduServices (from `../dadaedu-services`)
  - Firebase/Core
  - Google/Analytics
  - Google/SignIn
  - GoogleMaps (~> 1.13.2)
  - SDWebImage
  - UberRides (from `https://github.com/uber/rides-ios-sdk.git`, branch `swift-3-dev`)
  - VK-ios-sdk

EXTERNAL SOURCES:
  DadaeduServices:
    :path: ../dadaedu-services
  UberRides:
    :branch: swift-3-dev
    :git: https://github.com/uber/rides-ios-sdk.git

CHECKOUT OPTIONS:
  UberRides:
    :commit: 0152873cb5ac1cbcb557be930babdb97123c73aa
    :git: https://github.com/uber/rides-ios-sdk.git

SPEC CHECKSUMS:
  DadaeduServices: 23fb4b0b08203b0a9d027b9c0785eb3ddcbdb7d8
  Firebase: 4b66b5b59c43edac745b87f0c87e42cdd0279c13
  FirebaseAnalytics: e5fe8486efc01bec33f6bf82e2fa9fce4b124052
  FirebaseCore: 9691ee2ade70c098d7cf92440f4303f16d83ca75
  FirebaseInstanceID: b9eedd6846fb5e1f0f7279e1deaa7a7e4cf8392e
  Google: 98da4b1a60ed0beb80a290387a28333406a1eb90
  GoogleAnalytics: f42cc53a87a51fe94334821868d9c8481ff47a7b
  GoogleMaps: b20a103ff307f58392e603cf142e59d7e30374c1
  GoogleSignIn: d7ad83f13480e1f30453471d00d19b5293ac46af
  GoogleToolboxForMac: 8e329f1b599f2512c6b10676d45736bcc2cbbeb0
  GTMOAuth2: 7fc9c10f5c745f4d9850419ea88889fe3baa6b7d
  GTMSessionFetcher: 5ad62e8200fa00ed011fe5e08d27fef72c5b1429
  ObjectMapper: 3d571bb5af471c779e1160828cd9ad5c4ef90958
  SDWebImage: 0e435c14e402a6730315a0fb79f95e68654d55a4
  UberRides: 796f4335121c2c8223985329c6979a452edfe083
  VK-ios-sdk: 7fd48bc5aaa6b96c3197c1987eb6593f2ea67331

PODFILE CHECKSUM: b01a49e11c3c9196bea68d0d6f1e9b1e1aad98eb

COCOAPODS: 1.2.1
`

Do I need to open a new issue to have availability of closing that?

**Comment by edjiang** [comment]
@eli7ah, this issue is fine. Your `Podfile.lock` looks fine. Can you please confirm the error you're seeing?

**Comment by eli7ah** [comment]
@edjiang, yes, I also have many errors kind of it only in ObjectMapper framework

**Comment by edjiang** [comment]
Hm. I just tried starting a new project and installing the UberRides pod and could not get a build error.

Could you please try doing that as well and reporting back with your results? If it builds correctly, is there a way you can get into this state? Instructions to replicate will help me fix your problem :)

**Comment by edjiang** [comment]
We are now on v0.7.0, which adds Swift 4 support! If you are using Swift 3, you can still link to it when using Xcode 9. 

Let me know if this solves the issue you're having :)

https://github.com/uber/rides-ios-sdk/releases/tag/v0.7.0
