### ISSUE TITLE
Swift 4 support 

### ISSUE THREAD

**Issue by s-shahid** [uber/rides-ios-sdk#174]
Hi,

Could you please inform as to what is the status for swift 4 support , i m trying to build using Xcode 9 .

Getting error while compiling with Xcode 9 - "Module compiled with Swift 3.1 cannot be imported in Swift 3.2"

Cartfile : github "https://github.com/uber/rides-ios-sdk.git" "swift-3-dev"

Thanks,
Mohammed Shahid.

**Comment by edjiang** [comment]
Hey @s-shahid,

We're currently working on Swift 4 support in the `swift-4` branch, but the API is unstable and may change at any moment :)

To fix the error that you're getting, run the following commands in the terminal:

```bash
rm -rf source/Vendor/
carthage bootstrap --platform ios
```

This should rebuild your dependencies and get rid of that module error :)

**Comment by s-shahid** [comment]
Thats cool :) Will try that fix .

**Comment by edjiang** [comment]
@s-shahid:

We are now on v0.7.0, which adds Swift 4 support!

https://github.com/uber/rides-ios-sdk/releases/tag/v0.7.0

**Comment by s-shahid** [comment]
Thanks a lot @edjiang 👍
