### ISSUE TITLE
Manually adding subproject gives errors

### ISSUE THREAD

**Issue by SNagra** [uber/rides-ios-sdk#18]
Manually adding in the subproject as explained in the Readme gives the following errors. 

<img width="445" alt="screen shot 2016-04-15 at 3 55 52 pm" src="https://cloud.githubusercontent.com/assets/1387954/14576950/ba5ed7ac-0322-11e6-9203-3b97a9d8eb21.png">

**Comment by jbrophy17** [comment]
Hmmm I'm seeing similar issues, and here's how I got it working:

#### If you don't want to use CocoaPods at all:

Drag the UberRides project into your project as a subproject (as stated in the Readme)

Click on the UberRides.xcodeproj sub project and open the `General` tab. Under `Linked Frameworks and Libraries` delete the `Pods.framework` entry

Now click on `Build Phase` (still in the UberRides subproject) and delete the `Check Pods Manifest.lock` & `Copy Pods Resources` script phases

Now we need to get our dependencies. Clone the ObjectMapper dependency [found here](https://github.com/Hearst-DD/ObjectMapper) (we use version 1.1.5)

Once you have that, also drag the ObjectMapper.xcodeproj into your project

Click back onto the UberRides subproject, go to the `General` tab and click the `+` button under `Linked Frameworks and Libraries`

Choose the ObjectMapper iOS framework

Now build your project and everything should be good to go

#### If you do want to use CocoaPods partially:

Clone the UberRides repo

Go into the rides-ios-sdk/source folder and run `pod install`

Drag the UberRides.xcodeproj into your project as before

Also drag the Pods.xcodeproj into your project (found in rides-ios-sdk/source/Pods)

Build your project and everything should be good to go

#### If you want to use CocoaPods totally:

Just add `pod 'UberRides'` to your Podfile :)


======

Give it a shot and let me know if everything is working. Will update the Readme accordingly

**Comment by SNagra** [comment]
It does build and run for me now!
One more suggestion, perhaps add in the directions to remove the "Configurations" in the Project tab for UberRides to help get rid of a couple of more warnings because they look like they are just there for CocoaPods.

**Comment by jbrophy17** [comment]
Awesome, glad to hear it's all working.
Good catch on the configurations, I'll add that to the README
