### ISSUE TITLE
Getting a undeclared identifier 'UBSDKConfiguration' error

### ISSUE THREAD

**Issue by Jamongkad** [uber/rides-ios-sdk#19]
Hello, I installed Uber Rides SDK via Cocoapods and imported <UberRides/UberRides-Swift.h> in my AppDelegate.m file. Is there anything I missed?

**Comment by faarwa** [comment]
Are you working in the `.xcworkspace/` project in Xcode that was generated from running `pod install`?

Here's some sample code that works:
```objective-c
#import "AppDelegate.h"
@import UberRides;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [UBSDKConfiguration setSandboxEnabled:YES];
    // Override point for customization after application launch.
    return YES;
}
```

Hope this helps!

**Comment by Jamongkad** [comment]
Yup! I've been using the old SDK stuff in the form of 
` [[RidesClient sharedInstance] configureClientID:@"My Client Code"];`

So what I'm wondering now is going on? I already did an `pod update`.

**Comment by jbrophy17** [comment]
Still having trouble? Make sure it installed version 0.4.0
I've also noticed that Xcode complains about an undeclared identifier until you build your project again  (command + B) after installing new pods. Can you try that and see if it fixes it

**Comment by Jamongkad** [comment]
Hi John! Yes you are correct. Had to do a pod update and (command + B) to
shut XCode up. Thank you for the quick replies!👍

**Comment by jbrophy17** [comment]
No problem, glad everything is working :)
