### ISSUE TITLE
Unable to subclass RideRequestViewController

### ISSUE THREAD

**Issue by codyrotwein** [uber/rides-ios-sdk#191]
Can you change RideRequestViewController to open instead of public so that I can override/subclass it?

**Comment by edjiang** [comment]
Just curious, what are you trying to accomplish with the subclass? We may be making some changes in this area in the near future, so we don't want to accidentally break subclasses. 

Otherwise, you might be able to get by for now by copy-pasting the `RideRequestViewController`.

**Comment by codyrotwein** [comment]
Thanks for getting back to me Edward. I'm mainly subclassing it in order to
update the navigation bar buttons, as well as do some custom things related
to the menu controller I'm using in my app and some analytics type stuff.

I'd rather not have to copy-paste RideRequestViewController or modify the
Uber source. Please let me know if you guys have plans to change it to open.

Thanks,
Cody

**Comment by edjiang** [comment]
Ride Request Widget was deprecated in 0.9, so I'm closing this as a non-issue anymore. Sorry!

https://github.com/uber/rides-ios-sdk/releases/tag/v0.9.0

https://developer.uber.com/docs/riders/change-log
