### ISSUE TITLE
Setting Product ID for RideRequesting behavior

### ISSUE THREAD

**Issue by Jamongkad** [uber/rides-ios-sdk#20]
Hello! I want to know if this is a bug. When I set the product id for let's say a Deep Link Behavior. I get the correct product on the Uber app. But when I switch to UBSDKRideRequestViewRequestingBehavior. The product does not seem to be highlighted. Did I miss something the implementation? Thanks!

    UBSDKRideParametersBuilder *builder = [[UBSDKRideParametersBuilder alloc] init];
    [builder setProductID:myRideData[@"productID"]];
    
    CLLocation *pickupLocation = [[CLLocation alloc] initWithLatitude:[originCoordsLat doubleValue] longitude:[originCoordsLng doubleValue]];
    [builder setPickupLocation:pickupLocation nickname:originAddress];
    
    CLLocation *dropoffLocation = [[CLLocation alloc] initWithLatitude:[destinationCoordsLat doubleValue] longitude:[destinationCoordsLng doubleValue]];
    [builder setDropoffLocation:dropoffLocation nickname:destinationAddress];
    // You can chain builder function calls

    UBSDKRideParameters *rideParameters = [builder build];

**Comment by faarwa** [comment]
Hello! The Ride Request Widget currently doesn't support pre-selecting the product ID; we're aware of the issue and are hoping to support this as soon as possible. Thank you for opening this thread, we'll update you here when product ID is supported!

**Comment by Jamongkad** [comment]
Oh ok...well please let me know once you do.

**Comment by faarwa** [comment]
Hey @Jamongkad, the product ID should now be highlighted if it's being set in the `UBSDKRideParameters` (no SDK updates required). We're making some improvements on the widget, but the functionality is available. Thanks for bringing this up!

**Comment by Jamongkad** [comment]
Awesome! Thank you!
