### ISSUE TITLE
Error: access token failed to save to keychain

### ISSUE THREAD

**Issue by heshamghandour** [uber/rides-ios-sdk#21]
Hello!

Quick question, the first time I login it gets stuck at login screen printing this error:
Error: access token failed to save to keychain

traced it and here is the part of the code failing:
```
if !TokenManager.saveToken(accessToken, tokenIdentifier: accessTokenIdentifier, accessGroup: keychainAccessGroup) {
            print("Error: access token failed to save to keychain")
        }
```

however if I close the app and open again, works great.
Am I missing something?

**Comment by jbrophy17** [comment]
Are you logging in by using the `LoginManager` or via the `RideRequestViewController`? Also, what version of iOS are you seeing this on? And is it in simulator or on device?

Saving the `AccessToken` should just work, so not sure what's going wrong

**Comment by heshamghandour** [comment]
Hi jbrophy, thanks for the quick reply.

Just called `requestBehavior.requestRide(rideParameters)` similar to how it's called when the button class when it is tapped.

Real device, iOS 9.2.1

**Comment by heshamghandour** [comment]
to be more specific

 ```
   func setObject(object: NSCoding, key: String) -> Bool {
        var keychainItemData = getKeychainItemData(key)

        let value = NSKeyedArchiver.archivedDataWithRootObject(object)
        keychainItemData[AttrAccessible] = kSecAttrAccessibleWhenUnlocked
        keychainItemData[ValueData] = value
        
        var result: OSStatus = SecItemAdd(keychainItemData, nil)
        
        if result == errSecDuplicateItem {
            result = SecItemUpdate(keychainItemData, [ValueData: value])
        }
        
        return result == errSecSuccess
    }
```
in the "KeychainWrapper" class is returning false :)

**Comment by jbrophy17** [comment]
When you say `requestBehavior` is that a `RideRequestViewRequestingBehavior`? And you're using that on its own (not via the `RideRequestButton`?

Would you mind putting a breakpoint in `setObject` and letting me know what the actual error code is (the value of `result` at the end)

**Comment by heshamghandour** [comment]
Yes exactly. 
here you go
result = (OSStatus) -34018

**Comment by heshamghandour** [comment]
this seems to not be a problem from your side:
http://stackoverflow.com/questions/29740952/osstatus-error-code-34018?rq=1

**Comment by jbrophy17** [comment]
Ah okay, sorry I couldn't be of more help

**Comment by heshamghandour** [comment]
Just in case someone else faces a similar issue. This is a bug (not related to the sdk) that only happens when running the app from xcode directly on the phone. That's why when I relaunched the app the 2nd time works fine.

Thanks for your help John.
