### ISSUE TITLE
Type 'UILayoutPriority' (aka 'Float') has no member 'defaultHigh' in LoginButton.swift

### ISSUE THREAD

**Issue by priyankamistry09** [uber/rides-ios-sdk#221]
Hi,

I am trying to add uberRides in my existing app using cocoapod.
In my pod file I have 
`    pod 'UberRides', '~> 0.8'
`
When I compile I am getting error,
`Type 'UILayoutPriority' (aka 'Float') has no member 'defaultHigh'`
in LoginButton, RideRequestButton,RideRequestViewController and in RidesUtil files.

I have read issues in other library they say that cocoapods have some issues with Swift 3.2 and swift 4.0

What should I do now?

Please suggest.

**Comment by edjiang** [comment]
If you get compilation errors with CocoaPods, you may be using Swift 3.2 or no Swift at all in your main target. In that scenario, CocoaPods will set the swift version incorrectly. To fix this, click on your Pods project and select the `UberRides` and `UberCore` targets. Search for the Swift Language Version property, and change it to "Swift 4.0".

**Comment by priyankamistry09** [comment]
Thanks @edjiang. It solved my problem. :)
