### ISSUE TITLE
login is not working in UBER 

### ISSUE THREAD

**Issue by sanjeev1994** [uber/rides-ios-sdk#225]
`let scopes: [UberScope] = [.profile, .places, .request]
                    let loginManager = LoginManager(loginType: .native)
                    let loginButton = LoginButton(frame: CGRect.init(x: (self.view.frame.width/2)-130, y: 20, width: 260 , height: 50), scopes: scopes, loginManager: loginManager)
                    loginButton.presentingViewController = self
                    loginButton.delegate = self
`

This is my code when I pressed sign in it goes to uber app and bounces back to same app automatically.

**Comment by edjiang** [comment]
What's the error you get?

**Comment by sanjeev1994** [comment]
It's working on my device while testing from the Xcode. When I release a build in testflight for others test it's not working. So I am not sure what error it's giving.

**Comment by edjiang** [comment]
You need to add the other users to your developers list for testing purposes, or get permission from Uber to use the `request` scope. 

https://developer.uber.com/dashboard/

Go here, click on your app, and click on the Developers tab for more info.
