### ISSUE TITLE
"Access to Information" page does not show up in Uber app, while doing native SSO authorisation

### ISSUE THREAD

**Issue by avinmore** [uber/rides-ios-sdk#231]
Hello There,
      I have integrated rides-ios-sdk for SSO authorisation in my native iOS application, It is working fine until I launch Uber app and open left menu. 

**Here is the use case**: 
1. Launched Uber application and open left menu in Uber app.
2. Performed SSO authorisation from my native iOS application. 

**Result**: 
**Access to Information** that is authorisation page does not show up, it just launches the Uber application.

**Workaround**: I have to kill Uber app and perform SSO again from my application, then it works.

Uber application version : **v3.299.10002**
Uber SDK version : **0.9.0** 
iOS version: **10.3.2** 
Deeplink: **uberauth://connect?third_party_app_name=my-app-name&callback_uri_string=com.XXXX.YYYY://oauth/consumer&client_id=XXXXXXXXXXXXXX&scope=all_trips&sdk=ios&sdk_version=0.9.0**

**Comment by edjiang** [comment]
Thanks for the report. We're aware of this bug, and have this in our backlog :) We'll keep you updated!

**Comment by edjiang** [comment]
This is fixed in iOS version 3.300.x; you'll see it released soon!

**Comment by edjiang** [comment]
How was your report on 3.299? Is that a typo? 3.299 isn't on the App Store yet.

**Comment by SandroGrzicic** [comment]
Are there any "states" within the Uber app for which a native SSO request is ignored? Specifically, the app was in the background after a ride, with the ride feedback request at the botto, and a native SSO request from our app didn't result in showing the "Access to Information" page - the Uber app went to the foreground and was showing the option to give feedback at the bottom. Going back to our app and then attempting native SSO again resulted in the same behaviour multiple times.

This is on the iPhone X (iOS 12.1)with Uber version v3.325.10003 and uber-rides SDK 0.10.

Thanks!
