### ISSUE TITLE
Getting error from AuthorizationCode login type.

### ISSUE THREAD

**Issue by alexsdi** [uber/rides-ios-sdk#234]
Error Domain=com.uber.rides-ios-sdk.ridesAuthenticationError Code=14 "Unable to interpret the response from the server." UserInfo={NSLocalizedDescription=Unable to interpret the response from the server.}

When I was tried to login using Authorizationcode "login type" I got above Error, Is something I done wrong? or Is there any other way to resolve it. 

Note : It is working when I was login using implicit "login Type"

Thanks!.. Waiting for your valuable reply.

**Comment by edjiang** [comment]
Hey @alexsdi, thanks for reaching out! 

You should refer to the conversation in #232 for more details on why this is happening, and how to resolve.
