### ISSUE TITLE
Deeplink in ios not able to detect if uber is present in the mobile or not.

### ISSUE THREAD

**Issue by pranavkth** [uber/rides-ios-sdk#237]
Device : Iphone 5
Os : Ios 10.3 

Hi I tried using deeplink in ios with above specifications but it takes me to appstore eventhough uber is installed in it.

I tried doing the same thing with ios 11.2 Ipone 6s and it was working properly.
Please look into this asap.
Please let me know incase you need more info.
And the page on browser keeps on asking open in app store on iphone 6s.

**Comment by edjiang** [comment]
Please add the uber url schemes to your Info.plist file.

See instructions here: https://github.com/uber/rides-ios-sdk#sdk-configuration
