### ISSUE TITLE
target has transitive dependencies that include static binaries: /Localytics/Localytics-iOS-3.5.1/libLocalytics.a

### ISSUE THREAD

**Issue by rikhm** [uber/rides-ios-sdk#24]
I am getting this error when trying to instal uber pod. Seems like this error is because of "use_frameworks!" in pod file but don't know the exact reason

**Comment by faarwa** [comment]
Hi @rikhm, do you have any other pods in your Podfile that could be depending on Localytics? 

My assumption is that the `use_frameworks!` required to install our SDK is breaking for other pods that have dependencies that include static libraries. I'll investigate further.

**Comment by jbrophy17** [comment]
Could you also let us know what version of CocoaPods you're using?

**Comment by rikhm** [comment]
Hi @faarwa,
Yep I am using Localytics. And it does seem its most likely due to the static library issue you mentioned.

@jbrophy17, 
I am using 0.39.0

**Comment by jbrophy17** [comment]
Hi @rikhm, with the latest version of Localytics I don't think this is an issue anymore. Can you confirm?

**Comment by rikhm** [comment]
Hi @jbrophy17 
Sorry but as of now I have removed the uber pod from my project. I won't be able to confirm this issue.

**Comment by jbrophy17** [comment]
Ah, sorry to hear that. 
The new Localytics framework is dynamic so it shouldn't have any issues around static binaries.
