### ISSUE TITLE
RideScopeType AllTrips missing

### ISSUE THREAD

**Issue by EPage-Ed** [uber/rides-ios-sdk#25]
The documentation mentions the AllTrips scope type, but it's not defined in RidesScope.swift.

**Comment by jbrophy17** [comment]
Good eye @EPage-Ed, 
Thanks for reporting the incorrect documentation. The AllTrips scope is not currently supported in the SDK, but we are planning to add it soon. Stay tuned!

**Comment by jbrophy17** [comment]
Fixed in [0.5.0](https://github.com/uber/rides-ios-sdk/releases/tag/v0.5.0)
