### ISSUE TITLE
setProductID

### ISSUE THREAD

**Issue by coderWind** [uber/rides-ios-sdk#27]
hi ,i want know     UBSDKRideParametersBuilder *builder = [[UBSDKRideParametersBuilder alloc] init];
                             [builder setProductID:@"a1111c8c-c720-46c3-8534-2fcdd730040d"];

setProductID:@"a1111c8c-c720-46c3-8534-2fcdd730040d"  what this is ,,  how get it

**Comment by akki6230** [comment]
Hi CoderWind,

ProductID is any UBER product's ID, you'll get products form here - https://developer.uber.com/docs/v1-products

**Comment by jbrophy17** [comment]
@akki6230 is correct, the available product IDs for a location can be obtained via the /products endpoint.
The product ID represents an Uber product (uberPOOL, uberX, uberXL, etc)

**Comment by coderWind** [comment]
@jbrophy17 @akki6230  thanks , i see
