### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by karthikasdas** [uber/rides-ios-sdk#28]
Hi,

My app was running successfully until i did a pod update. After pod update I tried clean build, close Xcode and open and build, etc but nothing worked. Its giving me 'Use of undeclared type 'RequestButton' ' and 'Type RidesClient has no member sharedInstance' (In line RidesClient.sharedInstance.configureClientID("")). Please help.

Thanks,

**Comment by faarwa** [comment]
Hey @karthikasdas, the recent updates to the SDK were indeed breaking. The `RidesClient` no longer has a shared instance, and your client ID can now be configured in your app's `Info.plist`. The `RequestButton` has been renamed to `RideRequestButton`. Check out the [Changelog](https://github.com/uber/rides-ios-sdk/blob/master/CHANGELOG.md) for some more detail on changes, and the [README](https://github.com/uber/rides-ios-sdk/blob/master/README.md) and sample apps for example code.

**Comment by Qix-** [comment]
why isn’t semantic versioning being used?

**Comment by jbrophy17** [comment]
@Qix- semantic versioning is being used. As this is still a 0.x release, it should not be considered stable and may contain breaking changes

**Comment by Jamongkad** [comment]
I ran into this same problem a couple of hours ago. Nearly tore my hair out looking for a solution. What worked for me though was nuking the ~/Library/Developer/Xcode/DerivedData directory. After that I was able to build and deploy to an iOS device successfully.
