### ISSUE TITLE
Carthage Compatible!

### ISSUE THREAD

**Issue by Dershowitz011** [uber/rides-ios-sdk#29]
Please make this Carthage Compatible. It'd be a whole lot easier to integrate with a project. Thanks!

**Comment by jbrophy17** [comment]
Hi @Dershowitz011, we are planning on making this Carthage compatible in an upcoming update. Stay tuned!

**Comment by Dershowitz011** [comment]
Thank you @jbrophy17 . Can you please tell me if i can add a custom button to my view and request uber ride on that button tap? And if i can how can i do it?

**Comment by jbrophy17** [comment]
@Dershowitz011 I'd be happy to help, but can you please open a new issue for it?

**Comment by willtrking** [comment]
+1, Carthage support would be great

**Comment by jbrophy17** [comment]
Fixed in [0.5.0](https://github.com/uber/rides-ios-sdk/releases/tag/v0.5.0)
