### ISSUE TITLE
Custom button ride summon! 

### ISSUE THREAD

**Issue by Dershowitz011** [uber/rides-ios-sdk#31]
Can you please tell me if i can add a custom button to my view and request uber ride on that button tap? And if i can how can i do it? @jbrophy17 @faarwa

**Comment by Dershowitz011** [comment]
I guess the easiest way to do is provide the developer a way to access the method or what exactly happens when any button (to request a ride like how the requestridebutton does) is tapped. So that the devs can either choose to use the uber button or their own button with the **SAME** action as that of requestridebutton. Thanks.

**Comment by jbrophy17** [comment]
Hi @Dershowitz011, to clarify, do you want a custom button that can present the Ride Request Widget, link into the Uber app for a ride, or programmatically make a request?

Currently you are able to do the first two, and an upcoming update will include the third.

You can use the `RideRequesting` protocol for this, simply make a custom button that can take a `RideRequesting` object and a `RideParameters` object. Then you can call `requestRide(rideParameters:)` as your button's action. You can use the predefined `RideRequestViewRequestingBehavior` or `DeeplinkRequestingBehavior` as your `RideRequesting` object to present the Ride Request Widget or deeplink into the Uber app, respectively.

**Comment by Dershowitz011** [comment]
I want a button which does exactly what the **RequestRideButton** does. How it takes in the action when it is pressed, I should be able to do that with my own button. Can I do that? @jbrophy17

**Comment by Dershowitz011** [comment]
And @jbrophy17 could you please show me with an example as to how do what you've told? Just for clarity sakes. Thanks.

**Comment by Dershowitz011** [comment]
> You can use the RideRequesting protocol for this, simply make a custom button that can take a RideRequesting object and a RideParameters object. Then you can call requestRide(rideParameters:) as your button's action. You can use the predefined RideRequestViewRequestingBehavior or DeeplinkRequestingBehavior as your RideRequesting object to present the Ride Request Widget or deeplink into the Uber app, respectively.

**Comment by jbrophy17** [comment]
Happy to help :) Sounds like you got it working, but for just for reference, I was thinking something like this:
```
public var rideParameters: RideParameters
public var requestBehavior: RideRequesting

public init(rideParameters: RideParameters, requestingBehavior: RideRequesting) {
        requestBehavior = requestingBehavior
        self.rideParameters = rideParameters
        super.init(frame: CGRectZero)
        addTarget(self, action: #selector(buttonTapped(_:)), forControlEvents: .TouchUpInside)
    }

func buttonTapped(sender: UIButton) {
        requestBehavior.requestRide(rideParameters)
    }
```
