### ISSUE TITLE
How can I use it if I have no Uber app?

### ISSUE THREAD

**Issue by zhangchunsheng** [uber/rides-ios-sdk#4]
How can I use it if I have no Uber app?

**Comment by christinekim** [comment]
If you don't have the app installed, the button will redirect to the Apple app store where you can download the Uber app.

Ultimately, to request a ride, you will need an Uber account and the Uber application installed on your device.

**Comment by aasatt** [comment]
@christinekim Is there anyway to override this? I don't like this or the fallback. I would rather provide my own OAuth flow.

**Comment by jbrophy17** [comment]
Hi @aasatt, can you please open a new issue for your request? It is possible to supply custom logic to the buttons and I'll be happy to point you in the right direction
