### ISSUE TITLE
RidesAuthenticationError Code 18: "The Redirect URI provided did not match what was expected."

### ISSUE THREAD

**Issue by aasatt** [uber/rides-ios-sdk#41]
I have the URL Scheme in my .plist configured with the traditional URI but I am unable to set this in the Uber dashboard as is needs an HTTPS URL. Am I missing something?

**Comment by jbrophy17** [comment]
Hi @aasatt, sorry to hear you're having trouble. Could you provide a little more information on your URL Scheme? 
You should be able to set your app specific URI in the developer dashboard, however, it does require an authority. So for example, `sample://connect` would be valid, but just `sample://` would not. (You would then also use `sample://connect` as your UberCallbackURI in your .plist)

**Comment by aasatt** [comment]
@jbrophy17 Awesome thanks. Works now.

**Comment by jbrophy17** [comment]
Glad I could help! Opened #43 in relation to this
