### ISSUE TITLE
Update Getting Started Guide to be clearer

### ISSUE THREAD

**Issue by jbrophy17** [uber/rides-ios-sdk#43]
The getting started guide has been a point of some confusion. Could benefit from breaking it down into an easy to follow, step by step process

**Comment by timcamber** [comment]
I'd definitely agree. Still working through "Getting Started" and have yet to get things started.

**Comment by jbrophy17** [comment]
@timcamber we are actively working on making it easier to get up and running. Please feel free to comment here with any specific sections you are having trouble with

**Comment by timcamber** [comment]
Great! Thanks! I'd say the main issue I ran into was getting the URL callback to be just right, and to match what's in the mobile app's `plist` file with what appears in the app's section in the developer portal ("Redirect URL" under "Authorizations"). It wasn't totally clear to me whether each should specify the host, or the host and the path, or something else.

I also ran into the App Transport Security issue blocking network traffic, which I was able to quickly figure out, but which the Uber error message offered no insight into. Might be worth just mentioning in the "quick start" guide.

Let me know if any of this is unclear and I can be a bit more specific!

**Comment by timcamber** [comment]
I'll also say, I downloaded and tried to run the sample app and setting up dependencies with Carthage didn't work as described in the `README`, and I couldn't easily get the sample project to build. Maybe it was because I was using macOS Sierra betas. Eventually I got my sample project working, though.
