### ISSUE TITLE
Documentation unclear about Server Token in info.plist

### ISSUE THREAD

**Issue by hardikdevios** [uber/rides-ios-sdk#51]
Hello as it documented in the the section 

> All the button needs to gather this additional information is your **server token** to be configured in the **Info.plist** as described in the **SDK Configuration** section. To display a time estimate, set the product ID and pickup location. To display a price estimate, you need to additionally set a dropoff location

So when I go back to **SDK Configuration** section i am unable to find the information for which **server token** key is going to be used in the app info.plist. am i missing something ?
Attaching screenshot please confirm Server token key

![screen shot 2016-07-04 at 1 24 56 pm](https://cloud.githubusercontent.com/assets/6657591/16554168/c040787c-41ea-11e6-8d5f-0ce9b865ff92.png)

**Comment by gask** [comment]
I'm having the EXACT same doubt about this.
How am I supposed to set the server token in the Info.plist?
The SDK Configuration section here doesn't say anything about it.

**Comment by faarwa** [comment]
`UberServerToken` is the correct key to set in `Info.plist` (this seems to be missing in the SDK Configuration as you said).

**Comment by hardikdevios** [comment]
Ok great cheers guys 👍

**Comment by jbrophy17** [comment]
Sorry for the confusion, I will be sure to update the documentation for the next release

**Comment by gask** [comment]
Just a reminder that the docs wasn't updated up until now.

**Comment by jbrophy17** [comment]
Sorry about that, the last release was not a scheduled release and we have not yet had a chance to work through all the documentation updates. 

If you want, you could open a PR with what you expected the docs to say and I would be happy to review it

**Comment by jbrophy17** [comment]
Fixed in [v0.5.3](https://github.com/uber/rides-ios-sdk/releases/tag/v0.5.3)
