### ISSUE TITLE
Add a callback / notification to indicate trip status from the Ride Request Widget

### ISSUE THREAD

**Issue by jbrophy17** [uber/rides-ios-sdk#53]
Currently the Ride Request Widget only exposes a delegate for errors. It would be useful to expose some indicator of the trip status, as it changes. Possibly via the delegate or a notification.

**Comment by jbrophy17** [comment]
see #54

**Comment by arogal** [comment]
We may want to do this via API call instead. Something like a get to
/current with limited info.

**Comment by jbrophy17** [comment]
That is a possibility, we will need to think about how to handle the app being backgrounded as well

**Comment by gask** [comment]
Guys do we have a follow-up on this?

**Comment by edjiang** [comment]
Ride Request Widget was deprecated in 0.9, so I'm closing this as a non-issue anymore. Sorry!

https://github.com/uber/rides-ios-sdk/releases/tag/v0.9.0

https://developer.uber.com/docs/riders/change-log
