### ISSUE TITLE
Uber DeepLink Button Trigger

### ISSUE THREAD

**Issue by nassifbasheer** [uber/rides-ios-sdk#66]
I have integrated an Uber button request with deeplink , when the button is pressed there is a selected state color, is there a way to change the selected state color to clear color , is there a way to get a call back such that the deeplink is triggered

**Comment by jbrophy17** [comment]
Currently it is not possible to customize the color of the buttons outside of the two provided styles (see #59) 

I'm a little confused by what you mean when you say "is there a way to get a call back such that the deeplink is triggered". Do you mean just know when a user taps the button? The Uber Button is just a subclass of the standard button, so you could add another target to the button that does whatever you want when the user taps it.

**Comment by nassifbasheer** [comment]
Thanks for the update. I was actually looking for a delegate action if a deeplink button was pressed.

**Comment by jbrophy17** [comment]
Currently, there is no delegate action for when the button is just tapped. But as I mentioned, you can get similar functionality by adding another action to your button

for example
```
button.addTarget(self, action: #selector(buttonWasTapped(_:)), forControlEvents: .TouchUpInside)

@objc func buttonWasTapped(button: UIButton) {
    // Your logic here
}
```
