### ISSUE TITLE
UBSDKRidesAppDelegate not found

### ISSUE THREAD

**Issue by Moeez007** [uber/rides-ios-sdk#67]
Hello Guys, when i copy and paste this method in my appdelegate , I get an error that UBSDKRidesAppDelegate not found. Please help

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
    BOOL handledURL = [[UBSDKRidesAppDelegate sharedInstance] application:app openURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey] annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
    
    if (!handledURL) {
        // Other URL logic
    }
    
    return true;
}
```

**Comment by jbrophy17** [comment]
Did you forget to add `#import <UberRides/UberRides-Swift.h>`  ?

**Comment by Moeez007** [comment]
Sorry for the late reply. No, I have added that in appdelegate and also in my viewcontroller where this code is placed.

**Comment by jbrophy17** [comment]
Are you seeing any similar errors in your view controller? It looks like the SDK might not be added correctly to your project. What method did you use to integrate?

**Comment by Moeez007** [comment]
Again sorry for the late reply mate. the issue was that when I added the pod in my project, I left the line use frameworks inside the project name block, due to which some classes were not being found. Now it is resolved, thanks.
