### ISSUE TITLE
Uber SSO login issue in iOS 8 Swift 2.2

### ISSUE THREAD

**Issue by utsavhacker** [uber/rides-ios-sdk#69]
I am trying to integrate Uber Ride SDK in my app. 

Use this code to add Uber login button 

```
whiteLoginButton = LoginButton(frame: CGRectZero , scopes: [.Profile, .Places], loginManager: LoginManager(loginType: .Native))
whiteLoginButton.presentingViewController = self
whiteLoginButton.delegate = self
whiteLoginButton.colorStyle = .White
blackView.addSubview(whiteLoginButton)
```
and for delegation use this 

```
extension ViewController : LoginButtonDelegate{
    func loginButton(button: LoginButton, didLogoutWithSuccess success: Bool) {
        self.showMessage("Logout Success")
    }
 func loginButton(button: LoginButton, didCompleteLoginWithToken accessToken: AccessToken?, error: NSError?) {
        if accessToken != nil {
 self.showMessage("Got an AccessToken!")
   } else {
            // Error
    }
}
```
Code not working for native type login in app. 
In details SSO login not redirect from **official uber app back to my app with access token**.

**all callback URL and settings are verified from other sample and working in IOS 9+**

**Comment by jbrophy17** [comment]
Sorry to hear you're running into trouble. To clarify, you are unable to link back into your app from the native Uber app? Is there any error message that is displayed?

**Comment by utsavhacker** [comment]
No any error message displayed from Uber App. 

When click on login(LoginButton) from my app then it is redirect to Official Uber app and asking for allow access for Uber user profile.  But When I click on 'Allow' button then it is not redirect to my app, and unable to login using SSO, still implicit login are working in iOS8. 

Both type of login and other functionality(that i tested) are working with iOS 9 with same code.

**Comment by govindprasadguptacool** [comment]
I am facing same issue on iOS 8. On iOS 9 is working fine.

**Comment by govindprasadguptacool** [comment]
Now I am able to redirect but getting "error=unavailable" in redirect URL.

**Comment by jbrophy17** [comment]
Sorry, wasn't clear in my previous comment. That is the expected behavior for versions where this bug is present, the error indicates that SSO is unavailable for that version of Uber

**Comment by govindprasadguptacool** [comment]
We have latest Uber application:
Version: V2.147.2 which is released on 9 Aug 16

**Comment by jbrophy17** [comment]
It will be fixed in v2.148

**Comment by jbrophy17** [comment]
This should be resolved with the most recent version of the Uber app, no SDK update is required

**Comment by Ram-OAB** [comment]
I am also facing same problem. Uber app is asking me permission and then it goes to safari and stuck there saying Could not connect to server.
