### ISSUE TITLE
I accepted higher fare button is not working

### ISSUE THREAD

**Issue by govindprasadguptacool** [uber/rides-ios-sdk#75]
When I tap on "I accepted higher fare" button then a request is fired. After receiving response, nothing is happing and I am remaining on same UI.
![img_1223](https://cloud.githubusercontent.com/assets/19161360/17556145/facd74f6-5f2f-11e6-80e0-35b40c1bdd0b.jpg)

**Comment by chardane** [comment]
Hello! A couple questions to clarify here:

1. Would you be able to take a screenshot of the UI that you are stuck on after the request is fired?
2. Do you have `Configuration.setSandboxEnabled(true)` in your AppDelegate?
3. What device and OS version are you using?

This information will help in identifying your issue.

**Comment by govindprasadguptacool** [comment]
1. Would you be able to take a screenshot of the UI that you are stuck on after the request is fired?
----I am stuck on same attached UI. Not navigating to any screen.

2. Do you have Configuration.setSandboxEnabled(true) in your AppDelegate?
--- We are setting NO for sandbox enabled.

3. What device and OS version are you using?
iOS 9 and 10 Beta, iPhone 6

**Comment by davidlimhk** [comment]
@govindprasadguptacool 

Have you configured the SURGE_CONFIRMATION_REDIRECT_URI on the app dashboard?
Please refer to [here](https://developer.uber.com/docs/rides/tutorials-rides-api#section-handling-surge-pricing) for more details.

**Comment by edjiang** [comment]
<img width="810" alt="screen shot 2017-07-11 at 2 38 04 pm" src="https://user-images.githubusercontent.com/918770/28091980-ac8cb558-6646-11e7-8a59-9e4d32437564.png">

Yes, please make sure you set the surge confirmation redirect uri on the app dashboard.

https://developer.uber.com/dashboard/
