### ISSUE TITLE
Not able to login OR call any other Uber api

### ISSUE THREAD

**Issue by Moeez007** [uber/rides-ios-sdk#78]
Hello Guys, I have correctly setup the app on developer.uber.com and also correctly followed each and every detail while integrating the sdk in my project, but when I use the ride widget sdk code and press the button [ride there with Uber] I get this error. Is it my Call back URI issue or is it that i am using in the simulator.Thanks.

-canOpenURL: failed for URL: "uberauth://connect?third_party_app_name=(My app name on uber)&callback_uri_string=OldPeopleApp://SSO&client_id=(My Client ID)&login_type=default&scope=ride_widgets&sdk=ios&sdk_version=0.5.1" - error: "(null)"

**Comment by jbrophy17** [comment]
That error is because your simulator doesn't have the Uber app installed, so it is unable to switch to it in order to do Single Sign On. If you test on a device with Uber installed everything should work as expected

**Comment by Moeez007** [comment]
Hello Yes this issue is not shown on on the actual device. Thanks for helping out.

**Comment by jbrophy17** [comment]
No problem :)

**Comment by hirenpanchal1608** [comment]
So what i need to do if i want to test in simulator.?
Is it possible to work with uber without installing uber app?

**Comment by ignivanisha** [comment]
s it possible to work with uber without installing uber app?

**Comment by gelosi** [comment]
@jbrophy17 is it still impossible to login with UberSDK on simulator ? Any help would be appreciated.

**Comment by edjiang** [comment]
@gelosi yes you can! As long as you don't need a privileged scope, it will fall back to a web view for authentication. See here: https://github.com/uber/rides-ios-sdk#login-with-uber

**Comment by gelosi** [comment]
@edjiang thanks! that was mostly desperate voice rather than expecting someone replies ) Actually, my current scope is exactly privileged, so, app stays as "must". The only problem with that is automatically cut off simulator from use :/

**Comment by edjiang** [comment]
Unfortunately you can't use SSO on the simulator. However, you can get a token by manually doing the Auth Token flow, or fetching the token on a physical device.

Then you can manually set the token on your simulator device: 

https://github.com/uber/rides-ios-sdk#custom-authorization--tokenmanager
