### ISSUE TITLE
How to send server token in the plist file.

### ISSUE THREAD

**Issue by Moeez007** [uber/rides-ios-sdk#79]
"All the button needs to gather this additional information is your server token to be configured in the Info.plist as described in the SDK Configuration section"

This is written in the documentation but in the SDK configuration section there is no info on how to set the server token in the plist file, please some one can guide me, thanks.

**Comment by jbrophy17** [comment]
You need to add it to your Info.plist under the `UberServerToken` key. Sorry for the confusion, see #51

**Comment by Moeez007** [comment]
ok sure Thanks.
