### ISSUE TITLE
Difficulty with manual integration 

### ISSUE THREAD

**Issue by ashottonoyan** [uber/rides-ios-sdk#8]
App with Uber SDK won't compile.

**Comment by faarwa** [comment]
Would you mind sharing your compilation error? Are you running `pod install` and opening the respective `.xcworkspace` project file for the respective examples?

**Comment by ashottonoyan** [comment]
No, I just downloaded the zip file, opened the Obj-C example and it would not run. The SDK was not linked, which I did myself, but when trying to run, the app is not able to get the images from the .bundle file.

**Comment by ashottonoyan** [comment]
The manual integration does not work either.

**Comment by faarwa** [comment]
Here are the steps I'm taking to run the Obj-C example app:
1. Download rides-ios-sdk.zip and unzip folder.
2. Go to examples/Obj-C SDK/.
3. Run `pod install` - this installs the UberRides dependency (requires Cocoapods https://cocoapods.org/)
4. Open `Obj-C SDK.xcworkspace` (running in `Obj-C SDK.xcodeproj` will not work)
5. Run.

If you've tried the above steps and they did not work, please copy and paste your compilation error here.

**Comment by ashottonoyan** [comment]
With pod install it worked. After adding it as Embedded Binary worked in my project too.

**Comment by ashottonoyan** [comment]
fatal error: unexpectedly found nil while unwrapping an Optional value

```
#1	0x0000000100e8f04c in RequestButton.(getImage in _1BC843BE53C9D0EAD7BBE45C42A0713E)(String) -> UIImage at /Users/ashottonoyan/Workspace/xcode/rad_ios/RAD/RAD/Vendor/Uber/UberRides/RequestButton.swift:165
```

**Comment by ashottonoyan** [comment]
It can't find the bundle. It works when I copy the file from the bundle to the project.

**Comment by faarwa** [comment]
If you look under Pods/UberRides/Resources in the Pods project, do you see a Media.xcassets folder containing a 'Badge' asset (without copying the file from the bundle)?

**Comment by ashottonoyan** [comment]
I'm not using Cocoa Pods, just manual integration.

**Comment by faarwa** [comment]
Ah, I see the issue. Thanks for reporting!

**Comment by ashottonoyan** [comment]
Dyld Message: Library not loaded: @rpath/UberRides.framework/UberRides

When doing distribution build, even my workaround didn't help.

**Comment by faarwa** [comment]
Is this error occurring when you run Product > Archive?

**Comment by ashottonoyan** [comment]
No, archiving and sending out beta build worked, but as soon as people launched the app, it was crashing. Then I checked with Xcode -> Window -> Devices console and was getting this message every time I try to launch and get it crashed.

**Comment by faarwa** [comment]
There's a flag under Build Settings > Build Options called "Embedded Content Contains Swift Code". Is this set to Yes?

**Comment by ashottonoyan** [comment]
Yes.
![screenshot 2016-01-26 19 48 51](https://cloud.githubusercontent.com/assets/612529/12585524/7c92d350-c45d-11e5-9174-3a4d6d2d86af.png)

**Comment by faarwa** [comment]
I'm trying to repro the issue you're running into. Is this export for Ad Hoc Deployment?

**Comment by ashottonoyan** [comment]
Enterprise In house. Can it be because of that?

**Comment by faarwa** [comment]
I found this article relating to the error you're receiving for enterprise builds: https://www.airsignapp.com/ios-apps-using-swift-crash-when-signed-with-inhouse-certificate/.
Take a look and see if the errors they had are similar to yours. It seems they solved their issue through creating a new certificate and provisioning profile. 

From an Apple Technical Q&A: "All Enterprise and standard iOS developer certificates that are created after iOS 8 was released have the new Team ID field in the proper place to allow Swift language apps to run." (https://developer.apple.com/library/ios/qa/qa1886/_index.html).

Let me know if you have any luck with this!

**Comment by ashottonoyan** [comment]
Still, why do I have to move out the resources from the bundle in order to make it work even as debug build?

**Comment by faarwa** [comment]
The resources for the manual integration are an issue I'm working to resolve, and there will be a fix available soon that doesn't require your workaround. 

I don't believe the enterprise build issue is related to this, however, so this may be something on your development/distribution account. Please let me know if you have reason to believe otherwise!

**Comment by ashottonoyan** [comment]
I'm about to test with new certificate/provisioning profile. Will keep you posted.

**Comment by ashottonoyan** [comment]
With new certificate/provisioning profile it did work! Thanks for your support!

**Comment by faarwa** [comment]
Glad you got that sorted out! A fix for the resources issue will be pushed to Github soon.
