### ISSUE TITLE
Button not showing fare and time

### ISSUE THREAD

**Issue by instadealApp** [uber/rides-ios-sdk#82]
We would like to show the new button with price and time estimates. It works when we use your example, leaving the pickup longitude and latitude and changing drop-off location even though the estimated fare is 1600$ (San Francisco/Seattle). It doesn't work If we try to get the location from the locationManager or even paste any other lat or long. 

We also removed the sandbox mode from the applicationDelegate

When we launch the app it shows as default the WAV( Wheelchair accessible rides) which were not available in the area. May be that's the problem? The cheapest option is not available so the button correctly doesn't show anything?

```
 let button = RideRequestButton()
        let ridesClient = RidesClient()
        button.translatesAutoresizingMaskIntoConstraints = false

        let lat = manager.location!.coordinate.latitude as Double
        let long = manager.location!.coordinate.longitude as Double
        print(lat) 
        print(long)

        let pickupLocation = CLLocation(latitude: 37.787654, longitude: -122.402760)   // -------- UBER example 
       // let pickupLocation = CLLocation(latitude: 47.605526, longitude: -122.336445) This are the correct coordinates that my locationManager returns. When I comment out this line, the time and price is not shown. ---- SEATTLE 
       let dropoffLocation = CLLocation(latitude: merchant_lat!, longitude: merchant_long!) // this is my dropOff lat and long declared as Double and it always works. 
        var builder = RideParametersBuilder().setPickupLocation(pickupLocation).setDropoffLocation(dropoffLocation)

        ridesClient.fetchCheapestProduct(pickupLocation: pickupLocation, completion: {
            product, response in
            if let productID = product?.productID {
                builder = builder.setProductID(productID)
                button.rideParameters = builder.build()
                button.loadRideInformation()
            }
        })
```

![thumb_img_2059_1024](https://cloud.githubusercontent.com/assets/18354997/17744936/b795982e-645e-11e6-97be-aad238ad110f.jpg)

**Comment by jbrophy17** [comment]
hi @instadealApp sorry for the delay. That is strange behavior, your thoughts that it might be due to passing in an unavailable product seem reasonable. When you get the result from the fetchCheapestProdcut call, is it the WAV product?

**Comment by instadealApp** [comment]
hi @jbrophy17, it started working by itself (unless you did something on your side). Now the button is showing everything and the WAV option is not even selectable anymore.  it was very strange indeed. Thanks for your reply.

` 
        if manager.location != nil {
            
        let pickupLocation = CLLocation(latitude: manager.location!.coordinate.latitude, longitude: manager.location!.coordinate.longitude)
        let dropoffLocation = CLLocation(latitude: merchant_lat!, longitude: merchant_long!)
        var builder =    RideParametersBuilder().setPickupLocation(pickupLocation).setDropoffLocation(dropoffLocation)
            
            
        ridesClient.fetchCheapestProduct(pickupLocation: pickupLocation, completion: {
            product, response in
            if let productID = product?.productID {
                builder = builder.setProductID(productID)
                button.rideParameters = builder.build()
                button.loadRideInformation()
            }
        })          
    }
`

**Comment by jbrophy17** [comment]
Glad to hear everything is working! Let us know if you see this issue again
