### ISSUE TITLE
Need to support iOS 7.0+ devices.

### ISSUE THREAD

**Issue by deepak4u2006** [uber/rides-ios-sdk#84]
I have used @optional tag of the Pods_$projectName$.framework, to let the code compile for iOS 7.0 deployment target. Apart from the warning:

> was built for newer iOS version (8.0) than being linked (7.1)

I am also getting error as

> Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UBSDKConfiguration", referenced from:
      objc-class-ref in AppDelegate.o

Any suggestion pls!!

**Comment by jbrophy17** [comment]
Hi @deepak4u2006, the SDK only supports iOS 8+. At this time, we do not have plans of adding support for older versions of iOS, but you are welcome to make a PR
