### ISSUE TITLE
Missing Scopes in GrantedScopes Array After Authorization

### ISSUE THREAD

**Issue by kjanoudi** [uber/rides-ios-sdk#86]
Given:
- App submits authorization request with `request` and `request_receipt` scopes
- App is authorized access to these privileged scopes 
- User has "allowed" access to the scopes at time of authorization

Issue: 
- The returned GrantedScopes array does not contain the correct scopes returned from the uber authorization endpoint.

Cause:
- https://github.com/uber/rides-ios-sdk/blob/7e4a08c9acecfb24e93830eb4afe77345f23507a/source/UberRides/Model/RidesScope.swift#L164

I will attempt a PR for this - however, I am not an iOS developer so cannot personally test the changes myself

**Comment by jbrophy17** [comment]
Thanks for opening this issue. It looks like you have correctly identified the source of the bug, I will take a look at your PR

**Comment by jbrophy17** [comment]
Fixed in [v0.5.3](https://github.com/uber/rides-ios-sdk/releases/tag/v0.5.3)
