### ISSUE TITLE
Newbie question for using Uber button with Swift

### ISSUE THREAD

**Issue by kwstasna** [uber/rides-ios-sdk#88]
Hello.
Newbie question here.
I'm new to iOS dev. and I'm working on an app that will use Uber button.
My thought is to do the following.
There is a Club and i know the latitude and longitude of the club.
And also i know the users location.

First of all, what is the example of just opening the user's uber app and if he doesnt have it to open the Apple Store to download it? I dont want to "Login" within my app etc. Just to open your app with the user's Location and the Club's Location.

Secondly, what is callback://your_callback_uri ??? Where am i suppose to find it? My app doesn't use any website. I just got the bundle identifier. Any help of clearing this up? Because i've downloaded your example with swift but in `info.plist` file you have not entered any data.

Thanks a lot for your time!

**Comment by faarwa** [comment]
Hi @kwstasna, you can use the Ride Request Button with the Deeplink behaviour to accomplish this. 

```
let button = RideRequestButton()
let pickupLocation = // Your user's location
let dropoffLocation = // Club's location
let rideParams = RideParametersBuilder().setPickupLocation(pickupLocation).setDropoffLocation(dropoffLocation).build()
button.rideParameters = rideParams
button.requestBehavior = DeeplinkRequestingBehavior()
```
Check out the documents to see how to add `uber` as a URL scheme, and for examples of this.

For your second question, you have to populate the callback URI in the `Info.plist` with that registered to your client ID on the Uber Developers dashboard. This can be a custom URL scheme you may have for your app, for example: sampleApp://callback. If you're not doing SSO, you don't need to worry about implementing anything for this, just as long as the URL in your `Info.plist` matches that registered for your client ID.

**Comment by kwstasna** [comment]
@faarwa Thanks a lot for your info. Meanwhile I managed to check out the example app and figured out about Deep Linking. Everything works good.  :dancer:
