### ISSUE TITLE
Latitude/Longitude parameter type

### ISSUE THREAD

**Issue by ashottonoyan** [uber/rides-ios-sdk#9]
Would be more appropriate if the `setPickupLocationWithLatitude: longitude: nickname: address:` method would use `CLLocationDegrees` as type for longitude and latitude instead of `NSString`.

**Comment by faarwa** [comment]
This is a great idea. As we build out the rest of the SDK, we will be switching to functions that accept `CLLocationCoordinate2D` or `CLLocationDegrees` for latitude and longitude. Stay tuned!
