### ISSUE TITLE
Dubious "User cancelled the login process" errors

### ISSUE THREAD

**Issue by regosen** [uber/rides-ios-sdk#90]
(Using UberRides 0.5.2 via CocoaPods, tested on iPhone6 with iOS 9.3.4)

Immediately after obtaining a valid access token via deep link, our login methods themselves will sometimes return a nil accessToken with the following error:

```
com.uber.rides-ios-sdk.ridesAuthenticationError Code=25 "User cancelled the login process."
```

Note that I definitely did not cancel anything as the user.  All I did was press "Allow".  This has happened with both of the following methods (with AllTrips request):

```
(void)loginButton:(UBSDKLoginButton * _Nonnull)button didCompleteLoginWithToken:(UBSDKAccessToken * _Nullable)accessToken error:(NSError * _Nullable)error

[loginManager loginWithRequestedScopes:@[ UBSDKRidesScope.AllTrips ] presentingViewController: self completion: ^(UBSDKAccessToken * _Nullable accessToken, NSError * _Nullable error)
```

If we ignore the error and use the valid access token we had already received beforehand, everything seems ok.

**Comment by jbrophy17** [comment]
Hm, looks like a possible race condition when handling the deeplink. I will investigate more

**Comment by singh-bk** [comment]
I am facing a similar issue. Have attached the screen shot
![screen shot 2016-09-05 at 11 28 59 pm](https://cloud.githubusercontent.com/assets/1137961/18254904/908a6090-73c0-11e6-9f4c-02d5f5377599.png)

**Comment by Avinodh** [comment]
Hi I'm facing the exact same issue. After clicking the Uber Login Button in my app, I get redirected to the native Uber app where I click "Allow". I am redirected back to my app. However, I see the following error: 
Error Domain=com.uber.rides-ios-sdk.ridesAuthenticationError Code=25 "User cancelled the login process." UserInfo={NSLocalizedDescription=User cancelled the login process.}

Using Swift 3. Would appreciate any help!

**Comment by Avinodh** [comment]
Following up with respect to the above question @jbrophy17

**Comment by liaa** [comment]
I got the same problem here. Does anyone have any update on this? The Strange thing is I can run the Objective-C demo without this issue. 

I am using:
* Swift-3-dev branch
* In an objective-c code base

**Comment by edjiang** [comment]
Hey @liaa, @Avinodh, and @regosen:

Just double checking, but did you include the deep link handlers in your `AppDelegate`? They should look something like this:

```Swift
    @available(iOS 9, *)
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {
        
        return RidesAppDelegate.sharedInstance.application(app, openURL: url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplicationOpenURLOptionsKey.annotation] as AnyObject)
    }
    
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        return RidesAppDelegate.sharedInstance.application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation as AnyObject)
    }
```

**Comment by prgorasiya** [comment]
@edjiang I am also facing this issue and also when I click on Ok from error popup Uber app doesn't redirect to my own app and when I manually open my app console logs the same error message.

But in the backend of Uber it says I authorised my app to use Uber but actually Uber app throws me this error.

Any help?

**Comment by edjiang** [comment]
Did you register the URL scheme in your app's info.plist?

**Comment by nafetswirth** [comment]
I'm also seeing this but only for the first time when i press the Uber Login Buttun and the system shows me the alert "x" wants to open "Uber". 

After clicking allow and the redirect to my app i get:

`Error Domain=com.uber.rides-ios-sdk.ridesAuthenticationError Code=25 "User cancelled the login process." UserInfo={NSLocalizedDescription=User cancelled the login process.}`

Second login works fine so that makes me think it's not an issue in the configuration but i might be wrong.

**Comment by edjiang** [comment]
What iOS version and SDK version are you on, @nafetswirth?

**Comment by nafetswirth** [comment]
@edjiang SDK version is 0.8

iOS versions were 9.2, 10.2 and 11.2.1

**Comment by edjiang** [comment]
Hey all -- thanks for your patience on this. @lhasiuk has submitted what I believe is a fix to this problem in #222 -- will be verifying and cutting a release shortly :)

**Comment by edjiang** [comment]
Published to Cocoapods, 0.8.1. Thanks so much for your help!

**Comment by Avinodh** [comment]
@edjiang Been away from this project for a while, but back to working on it. Glad to see a fix for this was just released. Will test this and see if it works in my use case. Thanks for publishing this!

**Comment by shahiduos14** [comment]
**Solved :** 

Please following the official link which is based on Uber SDK 0.8 where the latest one has the issue which is 0.10.

Please use sample code from below link which is 0.8 uber sdk, without "login cancel issue". Following sample for android uber sdk is 0.8.

https://github.com/uber/rides-android-sdk

Please change to this one in Manifest file for LoginRedirectReceiverActivity

 <activity android:name=".auth.LoginRedirectReceiverActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.uber.sdk.android.core.uberauth"
                    android:host="redirect" />
            </intent-filter>
        </activity>

Rest is update your code with
 client id = your_client_id
server_token = your_server_token
redirect_uri = com.uber.sdk.android.rides.samples.uberauth://redirect


Happy Coding :)

**Comment by padsalanilay** [comment]
Hi @edjiang,
I am facing a similar issue. My app gets redirect to the Uber app and right after that it again gets redirected back, and I receive "User canceled the login process" error.
I have added code to AppDelegate and also have added required keys to info.plist
I am using a sandbox and have enabled it in a delegate.

ios - 13.5
cocoa UberRides - 0.13

Thanks
