### ISSUE TITLE
Uber permissions view doesn't appear if signin directed user to App Store first.

### ISSUE THREAD

**Issue by regosen** [uber/rides-ios-sdk#91]
(Using UberRides 0.5.2 via CocoaPods, tested on iPhone6 with iOS 9.3.4)
1. Uninstall Uber App (can be logged in or logged out)
2. Run third-party app with **setFallbackEnabled set to false**.
3. Initiate Uber signin (with AllTrips request), let Uber SDK redirect to App Store.
4. Download and launch Uber, login if prompted to do so.
5. **No "permissions" view appears.**
6. Return to third-party app manually, re-trigger Uber signin
7.  Get redirected to Uber app, but **still no "permissions" view.**
8. This time, **kill the Uber app.**
9. Return to third-party app manually, re-trigger Uber signin
10. **"Permissions" view appears, and works as intended.**

**Comment by jbrophy17** [comment]
Thanks for the in depth steps to reproduce. I will investigate this further

**Comment by jbrophy17** [comment]
With the latest version of Uber this should no longer be an issue
