### ISSUE TITLE
UberRides SDK adds 8MB to app download size

### ISSUE THREAD

**Issue by regosen** [uber/rides-ios-sdk#93]
(Using UberRides 0.5.2 via CocoaPods, tested on iPhone6 with iOS 9.3.4)

We noticed that if we switch to UberRides SDK from our previous web-based login implementation, our App Store binary size jumps from 7.5MB to 15.5MB.

This seems to stem from the addition of swift dylibs (UberRides SDK is the only swift library in our project).  Would you consider providing an Objective-C version of your CocoaPod?  If not, is there a more lightweight way to integrate your SDK?

**Comment by jbrophy17** [comment]
The SDK is written in Swift, there is no pure Objective-C version and we do not currently have plans to re-write it in Objective-C in the future. You are correct about the swift dylibs being added to your project, unfortunately that won't change until a stable version of swift is included with iOS.

The only lighter-weight option I can suggest is writing your own Objective-C implementation of the features you need based on this version & documentation available at the [Uber Developer site](https://developer.uber.com/docs/rides/tutorials-rides-api)
