### ISSUE TITLE
Deeplink to Uber App

### ISSUE THREAD

**Issue by russellbstephens** [uber/rides-ios-sdk#96]
Is there a way to deeplink to the uber app, and leverage the ParameterBuilders?  Seems like you need to use a url query?

**Comment by jbrophy17** [comment]
You can use the `RequestDeeplink` class. Just initialize it with a `RideParameters` instance and then you call `.execute(completion: ((NSError?) -> ())?)` to deeplink

**Comment by russellbstephens** [comment]
thanks,  is that in the README? ;)
